### PR TITLE
Add npm package link for Azure SDK instrumentation

### PR DESCRIPTION
**Pull request by maorleger**
**Preview**: https://deploy-preview-4626--opentelemetry.netlify.app/ecosystem/registry/?s=Azure+SDK+Instrumentation&component=&language=

### CODE REVIEW

**Comment by maorleger** [comment]
Pinged @lmolkova for EasyCLA auth as the owner

**Review by lmolkova — APPROVED** [review]
Thank you!

**Review by chalin — APPROVED** [review]
Thanks all for the updates and review.

**Pull request merged**
