### PR TITLE
add march otel in focus blog

### PR DESCRIPTION
**Pull request by austinlparker**
lousy smarch weather.

neither rain nor sleet nor highly communicable infectious respiratory disease will keep me from my appointed rounds of writing the march community update.

---

Preview: https://deploy-preview-2562--opentelemetry.netlify.app/blog/2023/otel-in-focus-03/

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
For releasage next month.

**Comment by chalin** [comment]
> neither rain nor sleet nor highly communicable infectious respiratory disease will keep me from my appointed rounds of writing the march community update.

🤣

**Review by chalin — COMMENTED** [review]
LGTM! See inline for minor copyedits.

I'm wondering if it would make sense to **publish the KubeCon post first**, and link to it from this post? @svrnm @cartermp et al., WDYT?

**Comment by cartermp** [comment]
I don't have much of an opinion about which post goes first. It's more important to have linkable announcements than assign an order. We can update the banner to point to the one we want the most eyes on.

**Comment by austinlparker** [comment]
Let's do this first and call-forward to it. I'm not precious about having these updates in the banner.

**Pull request merged**
