### PR TITLE
Update opentelemetry-java version to v1.44.0

### PR DESCRIPTION
**Pull request by opentelemetrybot**
Update opentelemetry-java version to `v1.44.0`.

See https://github.com/open-telemetry/opentelemetry-java/releases/tag/v1.44.0.

### CODE REVIEW

**Review by jaydeluca — APPROVED** [review]

**Review by chalin — APPROVED** [review]
LGTM once checks pass.

**Comment by chalin** [comment]
@jack-berg - can this be merged once the checks pass?

Related:

- #5566

**Comment by jack-berg** [comment]
> @jack-berg - can this be merged once the checks pass?

Yes, and so can #5566.

**Review by jack-berg — APPROVED** [review]

**Comment by chalin** [comment]
Rebased to kickstart the GH actions.

**Pull request merged**
