### PR TITLE
Fix code license, add NOTICE

### PR DESCRIPTION
**Pull request by svrnm**
The LICENSE-CODE file has a copy&paste error, fixed by this. I checked with other projects and the meaning of the license and the `Copyright [yyyy] [name of copyright owner]` should **not** be replaced by a project name.

I also added a NOTICE file as suggested by the apache license, see [section 4.4](https://www.apache.org/licenses/LICENSE-2.0.html#redistribution) for details. Although our repo does not have a lot of content, I think it still helps to improve potential attributions.

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
Out of curiosity: Is this something the Legal folks of CNCF should/could review?

**Comment by svrnm** [comment]
> Out of curiosity: Is this something the Legal folks of CNCF should/could review?

the change of the LICENSE file: no, the NOTICE file: maybe?

**Comment by svrnm** [comment]
I removed the NOTICE for now, because it may require more discussion

**Review by cartermp — APPROVED** [review]

**Comment by chalin** [comment]
Oh my, thanks for noticing that copy-paste error. There was back and forth some time ago in terms of which file(s) to use, I think that that's how it slipped 🤷🏼‍♂️ 

IMHO the LICENSE-CODE file needs further changes, the copyright notice is for the code in this repo, not the code in the documentation AFAIK. I'll open a separate issue to track this.

**Comment by chalin** [comment]
See:

- #3742

**Pull request merged**
