### PR TITLE
Update java libraries page to use intro shortcode

### PR DESCRIPTION
**Pull request by svrnm**
This PR updates the libraries page for java to use the intro shortcode, which uses common wording across languages and adds some words about out of the box instrumented libraries. I also updated the integrations entry for elastic search api library since it's the one java library that has "native" otel (all other integrations require a 1st party extension)

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
robot sad

**Comment by cartermp** [comment]
well poo, I think the 'ole refache fixer doesn't work anymore

**Review by theletterf — APPROVED** [review]

**Pull request merged**
