### PR TITLE
Update OpenTelemetry Dependencies

### PR DESCRIPTION
**Pull request by austinlparker**
Closes outstanding dependabot requests.

In addition, the web collector endpoint has been updated to v0.40.0.

### CODE REVIEW

**Comment by chalin** [comment]
If you open the Console over the preview, there are these errors, FYI:

```
deploy-preview-966--opentelemetry.netlify.app/:1 Access to resource at 'https://otelwebtelemetry.com/v1/traces' from origin 'https://deploy-preview-966--opentelemetry.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
otelwebtelemetry.com/v1/traces:1 Failed to load resource: net::ERR_FAILED
```

**Review by chalin — COMMENTED** [review]
Yay for the update!
See previous comment for Console log errors.

**Comment by austinlparker** [comment]
> If you open the Console over the preview, there are these errors, FYI:
> 
> ```
> deploy-preview-966--opentelemetry.netlify.app/:1 Access to resource at 'https://otelwebtelemetry.com/v1/traces' from origin 'https://deploy-preview-966--opentelemetry.netlify.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> otelwebtelemetry.com/v1/traces:1 Failed to load resource: net::ERR_FAILED
> ```

Yeah, the collector will only preflight from opentelemetry.io, not the preview site.

**Comment by chalin** [comment]
Ah, that makes sense, thanks!

**Comment by austinlparker** [comment]
I fixed the CORS policies to allow *.netlify.app as well to fix that.

**Comment by chalin** [comment]
Great, thanks.

**Pull request merged**
