### PR TITLE
Add OTLP to docs/specs

### PR DESCRIPTION
**Pull request by chalin**
- Contributes (possibly closes) #2642
- Adds the OTLP spec under `/docs/specs`

**Preview**: https://deploy-preview-2786--opentelemetry.netlify.app/docs/specs/otlp

/cc @tigrannajaryan

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
I think "Design Goals" and "Requirements" are unnecessary here. They contain text that is only of historical interest and is not part of the protocol spec.
We can probably keep just the "Specification" page and link it from the top-level "OTLP" link in the side navbar.
What do you think?

**Comment by tigrannajaryan** [comment]
> > I think "Design Goals" and "Requirements" are unnecessary here. They contain text that is only of historical interest and is not part of the protocol spec. We can probably keep just the "Specification" page and link it from the top-level "OTLP" link in the side navbar. What do you think?
> 
> That makes sense to me, but it's your call @tigrannajaryan, and that of @open-telemetry/specs-approvers.

Let's go with that. Remove "Design Goals" and "Requirements", only keep "Specification".

**Comment by chalin** [comment]
> Let's go with that. Remove "Design Goals" and "Requirements", only keep "Specification".

@tigrannajaryan - done. Only the OTLP spec page is not published. Also note that I've removed the proto files. Instead, links to proto files (and folders) point back to the repo.

**Review by tigrannajaryan — APPROVED** [review]
I think this is great.

**Review by cartermp — APPROVED** [review]

**Pull request merged**
