### PR TITLE
Update OpenTelemetry Documentation with addition of WSO2 API Manager as application integration

### PR DESCRIPTION
**Pull request by sanjeewa-malalgoda**
## Description
This pull request updates the documentation URL for the OpenTelemetry integration with WSO2 API Manager. The previous URL led to a general page, while the new URL directs users specifically to the page detailing how to monitor the WSO2 API Manager using OpenTelemetry. This change ensures that users have direct access to relevant and detailed information about implementing OpenTelemetry for enhanced observability.

## Impact
- Provides users with direct and precise documentation, improving ease of access and user experience.
- Ensures that the information is up-to-date and relevant to current integration capabilities between WSO2 API Manager and OpenTelemetry.

Thank you for considering this update. Please let me know if there are any further adjustments needed.

### CODE REVIEW

**Comment by theletterf** [comment]
Hi @sanjeewa-malalgoda ! Could you please sign the CLA?

**Comment by sanjeewa-malalgoda** [comment]
> Hi @sanjeewa-malalgoda ! Could you please sign the CLA?

Hi @theletterf, I have signed CLA. Thank you.

**Comment by tiffany76** [comment]
> I have signed CLA. Thank you.

Hi @sanjeewa-malalgoda, thanks for signing! It looks like one of your commits was made under a different login not covered by the CLA. You might want to squash that commit.

**Comment by svrnm** [comment]
@sanjeewa-malalgoda @isudana please take a look

**Comment by cartermp** [comment]
Closing out old PR

**Pull request closed without merging**
