### PR TITLE
Drop and ignore package-lock.json

### PR DESCRIPTION
**Pull request by chalin**
In the spirit of #582 -- for a website, it isn't worth the hassle of maintaining this under version control, IMHO.

cc @austinlparker

### CODE REVIEW

**Review by hdost — APPROVED** [review]

**Comment by mtwo** [comment]
I'll defer to @austinlparker on this one

**Comment by chalin** [comment]
As discussed with @tedsuo and @mtwo out-of-band, @austinlparker might be out for a while still. Besides, this is a simplifying PR that is easily "reversed".

@mtwo @flands - thoughts?

**Comment by chalin** [comment]
After discussion with @tedsuo, I'm going ahead and merging infrastructure PRs like these (in particular because this one is easy to revert).

**Comment by chalin** [comment]
Nope, apparently I don't have the permissions to do so.

**Review by mtwo — APPROVED** [review]

**Comment by chalin** [comment]
Thanks! 🎉

**Pull request merged**
