### PR TITLE
Adding go-instrument automatic instrumentation tool

### PR DESCRIPTION
**Pull request by nikolaydubina**

### CODE REVIEW

**Comment by cartermp** [comment]
@nikolaydubina you'll need to run `npm run fix` on your branch.

**Comment by nikolaydubina** [comment]
ok, just I just run `npm run fix`

**Comment by cartermp** [comment]
Unfortunately it seems you picked up some submodule changes. Could you discard those? Thanks!

**Comment by nikolaydubina** [comment]
@cartermp I do not know how to fix this. I made fresh PR here with fixed content. https://github.com/open-telemetry/opentelemetry.io/pull/4019

**Pull request closed without merging**
