### PR TITLE
Update Vendors to include Edge Delta

### PR DESCRIPTION
**Pull request by davereese**

### CODE REVIEW

**Comment by svrnm** [comment]
@davereese please sign the CLA!

**Comment by davereese** [comment]
> @davereese please sign the CLA!

I'm trying! I added my CTO as the CLA manager, but I don't know what else to do now

**Comment by svrnm** [comment]
> > @davereese please sign the CLA!
> 
> I'm trying! I added my CTO as the CLA manager, but I don't know what else to do now

You need to click the link provided by the easyCLA bot and click through the steps to be approved as a corporate contributor. Also, take a look into the easyCLA documentation for more details: https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors/corporate-contributor

**Comment by svrnm** [comment]
@davereese any updates on the CLA?

**Comment by theletterf** [comment]
Temporarily closing. I suggest we open a new PR once the CLA has been signed. Thanks!

**Pull request closed without merging**
