### PR TITLE
Added SolarWinds to vendor support list

### PR DESCRIPTION
**Pull request by danjagnow**
Added SolarWinds to **vendors.md**, the vendor support list.

### CODE REVIEW

**Review by cartermp — COMMENTED** [review]
Hmm, @danjagnow your link doesn't show anything about OpenTelemetry. Is there another place to link to?

**Comment by danjagnow** [comment]
> Hmm, @danjagnow your link doesn't show anything about OpenTelemetry. Is there another place to link to?

My apologies; I got a little trigger-happy.  Our content group hadn't pushed out the new content to that link yet.  If you check the same link now, you'll see the OTel integration documentation.

**Comment by cartermp** [comment]
Gotcha! Is there a link to a distribution (sdk or collector)? I couldn't find anything on the docs site about a distro.

**Comment by danjagnow** [comment]
> Gotcha! Is there a link to a distribution (sdk or collector)? I couldn't find anything on the docs site about a distro.

See https://github.com/solarwindscloud/solarwinds-apm-python and associated documentation at https://documentation.solarwinds.com/en/success_center/observability/content/configure/services/python/python.htm?cshid=app-add-python-agent.

**Comment by cartermp** [comment]
Thanks!

**Review by cartermp — APPROVED** [review]

**Pull request merged**
