### PR TITLE
Create instrumentation-go-kafka.yml

### PR DESCRIPTION
**Pull request by jurabek**
- Adding `confluent-kafka-go` instrumentation into registry

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks!

**Comment by cartermp** [comment]
@jurabek you'll need to move the file two levels up to be under `/data/registry`, not the nested folders of `/data/registry/data/registry`

**Comment by jurabek** [comment]
> @jurabek you'll need to move the file two levels up to be under `/data/registry`, not the nested folders of `/data/registry/data/registry`

I moved the file to the correct folder. Thank you very much @cartermp 🙏

**Pull request merged**
