### PR TITLE
Add HyperDX to vendors.yaml

### PR DESCRIPTION
**Pull request by MikeShi42**
Hello! We'd love to add HyperDX to the OpenTelemetry vendors list.

**OTLP Docs:** https://www.hyperdx.io/docs/install/opentelemetry
**Distribution**: We have a few SDK distributions such as [JS](https://github.com/hyperdxio/hyperdx-js) or [Python](https://github.com/hyperdxio/hyperdx-py) and even a [Deno logger](https://github.com/hyperdxio/hyperdx-deno).
**OSS**: Our project is MIT licensed and available here: https://github.com/hyperdxio/hyperdx/blob/main/LICENSE
**Contact**: support@hyperdx.io or @mikeshi42 (mike@hyperdx.io directly as well)

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
LGTM. Thanks Mike!

**Comment by svrnm** [comment]
@MikeShi42 I can not edit your PR and fix the refcache for you, please run `npm run test-and-fix` locally and make sure that the PR is up-to-date with main such that we are able to merge that PR eventually.

As a general piece of advice do never provide PRs from a fork within a GitHub organization, because they are read-only by default, please use your personal. Also work from a branch different to `main`, take a look at our Contribution Guidelines for more details: https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md#pr-guidelines

**Comment by MikeShi42** [comment]
@svrnm apologies for that, will definitely do for next time. I can also re-open the PR under a personal fork as well if easier.

**Comment by svrnm** [comment]
> @svrnm apologies for that, will definitely do for next time. I can also re-open the PR under a personal fork as well if easier.

No worries, this happens, you're lucky as I could just merge it, make sure to do this next time!

Thanks

**Pull request merged**
