### PR TITLE
fix Python Exporters page links to python packages

### PR DESCRIPTION
**Pull request by pegasas**
try to resolve: https://github.com/open-telemetry/opentelemetry.io/issues/3964

### CODE REVIEW

**Comment by theletterf** [comment]
Thanks! There's a refcache error though, please run `npm run text-and-fix` locally and then push the updated refcache file.

**Comment by theletterf** [comment]
Actually, let me do that for you.

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
thank you @pegasas !

**Pull request merged**
