### PR TITLE
docs: fix typo in ruby instrumentation

### PR DESCRIPTION
**Pull request by Go-pye**
Fix for a small typo / grammar issue

### CODE REVIEW

**Review by arielvalentin — APPROVED** [review]

**Comment by arielvalentin** [comment]
@Go-pye 👍🏼 assuming you are OK with signing EasyCLA

**Comment by Go-pye** [comment]
I signed the EasyCLA. It looks like the bot is having an issue linking my account. I did not have my git config `user.email` set before making this PR.

I'm not sure what to do next. Maybe close this PR and open a new one now that my email is set?

**Comment by chalin** [comment]
> I'm not sure what to do next. Maybe close this PR and open a new one now that my email is set?

Maybe you can try this first, which will sign the commit for DCO, but might be worth trying in this case too?

```console
$ git commit --amend --no-edit --signoff && git push -f
```

If that doesn't work, then resubmitting a PR would be great!

**Comment by Go-pye** [comment]
thanks @chalin but that didn't work. Here's the new PR #2324

**Pull request closed without merging**
