### PR TITLE
Improve consistency

### PR DESCRIPTION
**Pull request by joostlek**
In the Tracing part, opentelemetry is used instead of otel. This PR gives consistency in the naming

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
I'd maybe vote for `otel` throughout, but will defer to @svrnm and @cartermp

**Comment by chalin** [comment]
Just to be clear, I don't have a strong preference either way -- but I do agree that consistency is good! So thanks for submitting this PR.

**Review by pichlermarc — APPROVED** [review]
> @open-telemetry/javascript-approvers PTAL, is there any recommendation on that?

Looks good, I don't think there's a preferred way. I myself use `import opentelemetry from "@opentelemetry/api";` :slightly_smiling_face:

**Review by chalin — APPROVED** [review]
👍

**Pull request merged**
