### PR TITLE
add package version to JS entries in registry

### PR DESCRIPTION
**Pull request by svrnm**
Adds a `package` entry with `name` and `version` to most (all?) JS entries.

Preview: https://deploy-preview-3841--opentelemetry.netlify.app/ecosystem/registry/?language=js

cc @open-telemetry/javascript-approvers

### CODE REVIEW

**Comment by JamieDanielson** [comment]
Are these versions automatically updated or do they need to be kept up-to-date manually?

**Comment by svrnm** [comment]
> Are these versions automatically updated or do they need to be kept up-to-date manually?

They will be updated automatically (https://github.com/open-telemetry/opentelemetry.io/pull/3840)

**Comment by JamieDanielson** [comment]
> > Are these versions automatically updated or do they need to be kept up-to-date manually?
> 
> They will be updated automatically (#3840)

Ah you should've led with that 🤩  This seems pretty great actually

**Comment by svrnm** [comment]
> Ah you should've led with that 🤩 This seems pretty great actually

true, since I got this question twice 🤣 ... will keep that in mind for future PRs.

**Review by cartermp — APPROVED** [review]

**Pull request merged**
