### PR TITLE
Update architecture.md to remove incompatible link notation from diagram

### PR DESCRIPTION
**Pull request by theletterf**
Fixes https://github.com/open-telemetry/opentelemetry.io/issues/5168

### CODE REVIEW

**Review by mviitane — APPROVED** [review]
LGTM

**Comment by mviitane** [comment]
Not directly related to this PR, but this Telemetry Data Flow image looks too large compared to the Service Diagram (on the same page). Is there any setting for that?

**Comment by theletterf** [comment]
@mviitane We'd only control that through CSS classes, I'm afraid. Could you post a screenshot and your screen res?

**Comment by mviitane** [comment]
> @mviitane We'd only control that through CSS classes, I'm afraid. Could you post a screenshot and your screen res?

I have 2560 x 1440 screens, but in this screenshot, I'm using a somewhat narrow browser window. The font in the lower picture is much bigger than the upper pic (similar font size would work better). Also, the lower picture is so high that I cannot fit it on the screen at once.
Screenshot 2024-09-10 at 12 49 55

**Comment by monteiro-renato** [comment]
FYI: Looks like it's not completely fixed yet:
bilde

**Review by tiffany76 — APPROVED** [review]

**Comment by theletterf** [comment]
Let's merge till the bug gets fixed in Mermaid.

**Pull request merged**
