### PR TITLE
Update operator.md

### PR DESCRIPTION
**Pull request by michael-burt**
Fixes a bug in documentation, see here: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-operator/values.yaml#L240

### CODE REVIEW

**Comment by cartermp** [comment]
Thanks @michael-burt -- could you sign the CLA? That way we can review and merge.

**Comment by atoulme** [comment]
@cartermp would you mind please rerun the build?

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
Build checks are passing. Still waiting on the CLA though.

**Comment by atoulme** [comment]
:( maybe try opening a new PR @michael-burt in parallel to this one, and see if easyCLA gets the hint.

**Pull request closed without merging**
