### PR TITLE
Community roadmap: bring in via submodule

### LINKED ISSUE #2167: Highlight new project roadmap
We should highlight the existence of the [project roadmap](https://github.com/open-telemetry/community/blob/main/roadmap.md) via opentelemetry.io, a few things come to mind:

* We could update the banner with it
* Blog post?
* Have an official link somewhere or make a sync of it from the community repo?

### PR DESCRIPTION
**Pull request by chalin**
- Closes #2167
- Closes #2176

**Preview**: https://deploy-preview-2296--opentelemetry.netlify.app/community/roadmap/

### CODE REVIEW

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
❤️

**Comment by chalin** [comment]
Do we need more approvals, or can this be merged @svrnm @cartermp?

**Review by cartermp — APPROVED** [review]
Let us merge merge :)

**Pull request merged**
