### PR TITLE
Add Instana Agent as collector to the registry

### PR DESCRIPTION
**Pull request by tkohn**
Create new registry entry for the Instana Agent as collector

### CODE REVIEW

**Comment by austinlparker** [comment]
Could you sign the CLA?

**Comment by tkohn** [comment]
Done

**Comment by austinlparker** [comment]
@chalin any idea what's going on with the checks here? getting weird timeouts on netlify

**Comment by chalin** [comment]
@austinlparker - restarted the build. Let's see if we still get timeouts.

**Review by chalin — COMMENTED** [review]
Restarting the build seems to have fixed the issue.

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
weird, wonder why it timed out when i tried it? ah, well, technology.

**Pull request merged**
