### PR TITLE
Add explanation of the trace sample

### PR DESCRIPTION
**Pull request by melbgirl**
To assist OTel (and/or observability) newcomers to better understand.

### CODE REVIEW

**Comment by melbgirl** [comment]
Perhaps it would make sense to describe spans before traces; eg after the sample trace output, explain what spans are, and then go into what makes up a trace in OTel. The context of what is a span is useful for understanding the trace components.

**Comment by cartermp** [comment]
@melbgirl I think this would be better above the example, yep. Also, would you mind formatting the text to be the same width as the rest? I personally use [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) in vscode to automate that.

**Comment by melbgirl** [comment]
Done. I think it would also be helpful to add some pseudocode showing how to implement a span link - the textual description is great, but I found it hard to then apply it.

**Comment by austinlparker** [comment]
@cartermp is this g2g?

**Comment by cartermp** [comment]
Yarp!

**Review by cartermp — APPROVED** [review]

**Review by chalin — APPROVED** [review]
(FYI, I ran the markdown formatter.)

Thanks all!

**Pull request merged**
