### PR TITLE
Update manual.md

### PR DESCRIPTION
**Pull request by guangzhengli**
fix the dotnet manual doc to remove unused characters.

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
While the formatting of that link text might seem strange because the code font, I'd say that the original link text is ok.

Maybe we could rewrite the end of the sentence to something like:

> with [`Activity`](#) elements.

(or something similar) but I'll leave that decision up to the @open-telemetry/dotnet-approvers.

**Comment by svrnm** [comment]
I like @chalin's solution, makes it look a little bit neater. Do you want to change that accordingly @guangzhengli ? Also please sign the CLA that we can accept your PR

**Comment by guangzhengli** [comment]
I have created a new PR, is this the correct modification? #2950

**Comment by Kielek** [comment]
@guangzhengli, it should be fine. Typically you can modify existing PR by adding more changes to the current branch.

**Comment by chalin** [comment]
I had to run the formatter, and this PR has the revision history so I'll merge this one rather than #2950.

Closes #2950

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
Minor editorial change. Merging.

**Pull request merged**
