### PR TITLE
[outreachy] converted the add your project to the registry into a button

### PR DESCRIPTION
**Pull request by Isioma20**
For the second task given of suggesting a prototype design for an actual "add to the registry" page, 
I first thought to use a form but here are some reasons why I don't think it is feasible
### TECHNICAL FEASIBILITY
The site doesn’t currently have a backend hence it cannot store data collected through a form, ⁠and if we were going to try to create a Pull Request directly from the form submission, the GitHub API  doesn’t allow a seamless way to do that.
### WORKLOAD
Updating the registry would require someone on the Open Telemetry team to make each individual submission and entry into `the data file/data/registry directory`
### FEEDBACK
It is easier for maintainers to give feedback to contributors via Pull Requests when there is any questions regarding the input than to individually reach out when there are issues with the template entries.
After ideating on different add flows, 
I’ve concluded that the current page outlining the process to add projects to the Open telemetry registry is okay and fits to the current style of the website. The only modification I could play around with was making it into a modal but it’s not the best experience on mobile and it also doesn’t fit into the overall aesthetic of the website.

### CODE REVIEW

**Comment by svrnm** [comment]
Thank you for taking a look into the feasibility of adding a project, there are two alterntive options that still would be valuable:

* After filling out the form the user is presendet with a YML file to copy and instructions where to put it locally
* Although there is no pull request API, there is a capability to prefill a new file in the web editor, i.e. `https://github.com/open-telemetry/opentelemetry.io/new/main?filename=data/registry/test.yml&value=title:+My+Test%0Adescription:+my+test+description`

For the button itself, can you take a look how to make it more appealing and integrated into the UI.

**Comment by Isioma20** [comment]
Thank you for the feedback @svrnm . I'm currently working on the first item. For the button itself, I'd like to know what can be done to make it more appealing and integrated to the UI.

**Comment by svrnm** [comment]
@Isioma20 please make sure that you register with the outreachy platform after that I will provide a review

**Comment by Isioma20** [comment]
Thank you @svrnm. I have registered with the outreachy platform. looking forward to the review

**Comment by svrnm** [comment]
hey @Isioma20 , giving you a headsup that today is the last day I am able to help you here and make progress with this PR, please let me know if/how I can help you.

**Comment by Isioma20** [comment]
Hi @svrnm. Thank you. I'll update this pr before end of day today. I'd also like to inquire if we can continue to work after the application phase has closed

**Comment by Isioma20** [comment]
Hi @svrnm. I have edited the add your project button but still reviewing the UI. I have added an add to the registry form using the suggestions that you have previously given me. However, the vs code option isn't currently working

**Review by Mitrok-Bit — COMMENTED** [review]
- [x]

**Comment by Isioma20** [comment]
Hi @svrnm. I'd still love any feedback on this Pull request. Thank you!

**Comment by svrnm** [comment]
thanks for working on this during the outreachy application phase. I will close this PR for now, since we currently do not have the capacity to maintain this feature in the website.

**Pull request closed without merging**
