### PR TITLE
Add a note to 'Distributions' page to follow marketing and trademark guidelines

### PR DESCRIPTION
**Pull request by svrnm**
While doing some research for creating a distribution of OpenTelemetry I was looking for guidelines for using logo, name and other collaterals. I expected to find something on the page about [Distributions](https://opentelemetry.io/docs/concepts/distributions/), so after finding them [here](https://github.com/open-telemetry/community/blob/main/marketing-guidelines.md), I thought it would be good to have them where I was looking for them.

Preview: https://deploy-preview-1150--opentelemetry.netlify.app/docs/concepts/distributions/#what-you-should-know-about-distributions

### CODE REVIEW

**Review by chalin — APPROVED** [review]
LGTM (not the separate commit in which I tweaked the paragraph -- hoping that those edits are ok with you)

**Comment by chalin** [comment]
@tedsuo @austinlparker @cartermp - thoughts?

**Review by cartermp — APPROVED** [review]

**Comment by svrnm** [comment]
> hoping that those edits are ok with you

LGTM.

**Comment by chalin** [comment]
@austinlparker - I'm going to merge this now. If you have any points to address, we can do it in a followup email. Thanks.

**Comment by chalin** [comment]
Thanks @svrnm!

**Comment by austinlparker** [comment]
Sorry, meant to say lgtm. Been in meetings constantly today

**Pull request merged**
