### PR TITLE
Update discussion-group.md

### PR DESCRIPTION
**Pull request by reese-lee**
Updates the page with dates for the next few months for the End User Discussion meetings.

---

**Preview**: https://deploy-preview-3953--opentelemetry.netlify.app/community/end-user/discussion-group/

### CODE REVIEW

**Review by mhausenblas — APPROVED** [review]
LGTM and wondering, should we include a link to the recordings spreadsheet here as well?

**Review by svrnm — APPROVED** [review]
lgtm overall

**Comment by svrnm** [comment]
> LGTM and wondering, should we include a link to the recordings spreadsheet here as well?

Happy to have them added :-)

**Review by chalin — APPROVED** [review]

**Pull request merged**
