### PR TITLE
Update go/getting-started.md

### PR DESCRIPTION
**Pull request by ytnsym**
`otelslog.WithInstrumentationScope` does not exist.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks, good catch on the 5/21 release

**Review by dmathieu — CHANGES_REQUESTED** [review]
The API has changed (as it can in a pre-v1 version), and `WithInstrumentationScope` has been replaced by specific options (to remove the dependency on the SDK).
See https://github.com/open-telemetry/opentelemetry-go-contrib/pull/5588

**Review by dmathieu — APPROVED** [review]
Sorry, request changes by mistake.

**Comment by cartermp** [comment]
wooaaaahhh my god, okay, something in `main` changed that led to the formatter not being happy, sorry for the mass notification everyone

**Comment by cartermp** [comment]
This might be a consequence of https://prettier.io/blog/2024/06/01/3.3.0#improve-wrapping-for-markdown--mdx-16158httpsgithubcomprettierprettierpull16158-by-seiyabhttpsgithubcomseiyab

cc @chalin

**Comment by cartermp** [comment]
I am going to proceed with pushing this through for now, as it's not harmful and affecting other PRs.

**Comment by chalin** [comment]
Some of the newly formatted lines look off to me, but I'm ok sticking to whatever Prettier provides. Thanks @cartermp.

**Pull request merged**
