### PR TITLE
Update OpenTelemetry submodule to include the 1.15.0 schema.

### PR DESCRIPTION
**Pull request by carlosalberto**
cc @tigrannajaryan

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]

**Comment by chalin** [comment]
Update: so the link is valid, it's just external to the (local copy of the) spec. I'm working on a fix.

**Comment by chalin** [comment]
A fix is ready:

- https://github.com/open-telemetry/opentelemetry.io/pull/1978

Once it is approved and merged, this PR will need to be rebased to include it.

**Comment by chalin** [comment]
Note to self to address:

- #1850

After this PR is merged.

**Comment by chalin** [comment]
@carlosalberto - was this just meant to be a "test" PR? That is, do you want to wait for https://github.com/open-telemetry/opentelemetry-specification/pull/2925 to be merged first before updating the spec submodule?

**Comment by carlosalberto** [comment]
IIRC we want to merge this before we do the 1.15.0 Specification release. @tigrannajaryan should be able to confirm.

**Comment by tigrannajaryan** [comment]
Yes, according to the [release procedur](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#releasing)e this PR should be merged first.

**Comment by carlosalberto** [comment]
@chalin Ready ;)

**Pull request merged**
