### PR TITLE
chore: add missing ':'s in registry cSpell ignore lists

### PR DESCRIPTION
**Pull request by svrnm**
Not mandatory, but this creates consistency with other `cSpell:ignore:` lists we have

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
If we haven't yet, could we document this in a contribution guide together with other particularities of our docs? If that doc doesn't exist, I can create an issue and work on it.

**Review by cartermp — APPROVED** [review]

**Comment by simi** [comment]
I have not seen `ignore:` in docs, shouldn't it be opposite? Remove `:` in cSpell ignore lists? Or is there any reason to keep those in there?

https://cspell.org/configuration/document-settings/

**Review by chalin — CHANGES_REQUESTED** [review]
Catching up on PRs. @simi is right, we don't need a `:`, ... unless we're **encoding** the ignore rule as part of the **Hugo front-matter**. In such cases, we need the colon because `cSpell:ignore` is being used as a YAML key name.

I'd suggest not making these changes.

**Comment by chalin** [comment]
With @cartermp's thumbs up, I'm going to close this for now. @svrnm - feel free to reopen if you'd like to explore this further.

**Pull request closed without merging**
