### PR TITLE
Social-media image: use colored stacked logo

### PR DESCRIPTION
**Pull request by chalin**
- Contributes #1519
- I created the social media image from [opentelemetry-stacked-color.png], putting it into a ratio of 1.91:1, as [recommended by Facebook](https://developers.facebook.com/docs/sharing/webmasters/images), and by adding a bit of padding to the top and bottom, using this [ImageMagick](https://imagemagick.org/) command:
  ```console
  $ convert static/img/logos/opentelemetry-stacked-color.png -gravity center -background transparent -extent 1910x1000 static/img/social/logo-wordmark-001.png
  ```

Previews:

- Homepage: https://deploy-preview-1588--opentelemetry.netlify.app
- Other page: https://deploy-preview-1588--opentelemetry.netlify.app/docs/

[opentelemetry-stacked-color.png]: https://github.com/open-telemetry/opentelemetry.io/blob/68935931c9b7d7471d33d16a92b553e256a6e834/static/img/logos/opentelemetry-stacked-color.png

---

### Screenshots and tests

- **Facebook** debugger: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeploy-preview-1588--opentelemetry.netlify.app%2Fdocs%2F
- **Twitter** validator: https://cards-dev.twitter.com/validator
  Enter, for example, https://deploy-preview-1588--opentelemetry.netlify.app/docs/ yields:
  ```nocode
  INFO:  Page fetched successfully
  INFO:  18 metatags were found
  INFO:  twitter:card = summary_large_image tag found
  INFO:  Card loaded successfully
  ```
  > image

/cc @nate-double-u @thisisobate

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]
I like it, but I'd like to get more approvals than just me.

**Review by cartermp — APPROVED** [review]
@austinlparker you got it

**Comment by chalin** [comment]
Thanks!

/cc @svrnm

**Comment by svrnm** [comment]
@chalin , thanks for making this happen :-)

**Pull request merged**
