### PR TITLE
Fixing spelling error

### PR DESCRIPTION
**Pull request by harrison-kim**
Fixing spelling error found on the Collector configuration page: https://opentelemetry.io/docs/collector/configuration/

### CODE REVIEW

**Comment by austinlparker** [comment]
thanks!

**Comment by austinlparker** [comment]
please make sure you sign the CLA

**Comment by harrison-kim** [comment]
image
Is there something I can do to help kick off this check? 💻👈👀

**Comment by austinlparker** [comment]
Try toggling the PR between draft and not-draft? Maybe it got stuck...

**Comment by austinlparker** [comment]
Hm, that didn't seem to get it. Let me bug some folks.

**Comment by austinlparker** [comment]
@harrison-kim try closing and re-opening the PR entirely?

**Comment by harrison-kim** [comment]
> @harrison-kim try closing and re-opening the PR entirely?

Sure thing, I'll give it a go 🚪

**Comment by austinlparker** [comment]
huzzah

**Pull request merged**
