### PR TITLE
Update payment.md code sample to `require` `./index.js`

### PR DESCRIPTION
**Pull request by marleypowell**
The description paragraph mentions:
> It then requires your app at ./index.js to start it up once the SDK is initialized.

https://github.com/open-telemetry/opentelemetry.io/blob/9b9596e21766406b0d93b203fd1bf184f831111e/content/en/docs/demo/services/payment.md?plain=1#L21C1-L25C24

This seems to be missing from the code sample.

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
@open-telemetry/demo-approvers PTAL

**Comment by svrnm** [comment]
@open-telemetry/demo-approvers PTAL

**Comment by puckpuck** [comment]
This is not correct. What is missing is how you require this, which is done as part of the node command to start the app itself.

```
node --require ./opentelemetry.js index.js
```

**Comment by puckpuck** [comment]
```
ENTRYPOINT [ "node", "--require", "./opentelemetry.js", "./index.js" ]
```

**Comment by svrnm** [comment]
@marleypowell @open-telemetry/demo-approvers any more updates on this PR?

**Comment by svrnm** [comment]
@marleypowell @open-telemetry/demo-approvers PTAL

**Comment by puckpuck** [comment]
This PR in its current form, is not correct. The docs today are also not correct. See this comment on what the proper solution is, which would also require rewriting the paragraph description on the docs page: https://github.com/open-telemetry/opentelemetry.io/pull/4256#issuecomment-2043932874

**Comment by svrnm** [comment]
> This PR in its current form, is not correct. The docs today are also not correct. See this comment on what the proper solution is, which would also require rewriting the paragraph description on the docs page: [#4256 (comment)](https://github.com/open-telemetry/opentelemetry.io/pull/4256#issuecomment-2043932874)

thanks. @marleypowell can you fix the PR accordingly?

**Comment by marleypowell** [comment]
> > This PR in its current form, is not correct. The docs today are also not correct. See this comment on what the proper solution is, which would also require rewriting the paragraph description on the docs page: [#4256 (comment)](https://github.com/open-telemetry/opentelemetry.io/pull/4256#issuecomment-2043932874)
> 
> thanks. @marleypowell can you fix the PR accordingly?

I've updated it based on the suggestion 🙂

**Review by puckpuck — APPROVED** [review]

**Pull request merged**
