### PR TITLE
Missing 'are' in search-form

### PR DESCRIPTION
**Pull request by rockdaboot**

### CODE REVIEW

**Comment by rockdaboot** [comment]
My company should have signed the CLA. Not sure why the auto-detection doesn't work.

**Comment by cartermp** [comment]
Hrm. Is the email associated with your account here from Elastic?

**Comment by rockdaboot** [comment]
> Hrm. Is the email associated with your account here from Elastic?

Absolutely, the email from the commit is my official Elastic email.

**Comment by rockdaboot** [comment]
Oh wait, maybe I messed up when forking...

**Review by svrnm — APPROVED** [review]

**Pull request closed without merging**
