### PR TITLE
Update go code excerpts

### PR DESCRIPTION
**Pull request by svrnm**
Replaces #4678

### CODE REVIEW

**Review by chalin — APPROVED** [review]
Is this just a run of the code-excerpt tooling over the docs?
What's left to do (why the draft status)?

**Comment by svrnm** [comment]
> Is this just a run of the code-excerpt tooling over the docs? What's left to do (why the draft status)?

If I remember correctly a file was extracted (lines 411 to 423) and this needs to be added to the text. Tbh I forgot about this issue/didn't get to it

**Comment by pellared** [comment]
FYI the changes look wrong. See https://github.com/open-telemetry/opentelemetry-go/blob/main/example/dice/rolldice.go

**Comment by svrnm** [comment]
> FYI the changes look wrong. See [open-telemetry/opentelemetry-go@`main`/example/dice/rolldice.go](https://github.com/open-telemetry/opentelemetry-go/blob/main/example/dice/rolldice.go?rgh-link-date=2024-07-25T10%3A05%3A12Z)

the changes are based on the release we have pinned the submodule to (v1.27.0), we might need a more robust workflow here, especially when files are forked out

**Comment by pellared** [comment]
> the changes are based on the release we have pinned the submodule to (v1.27.0),

And we already have v1.28.0:
- https://github.com/open-telemetry/opentelemetry-go/blob/v1.28.0/example/dice/rolldice.go

**Comment by svrnm** [comment]
> > the changes are based on the release we have pinned the submodule to (v1.27.0),
> 
> And we already have v1.28.0:
> 
>     * [open-telemetry/opentelemetry-go@`v1.28.0`/example/dice/rolldice.go](https://github.com/open-telemetry/opentelemetry-go/blob/v1.28.0/example/dice/rolldice.go?rgh-link-date=2024-07-25T10%3A36%3A57Z)

That's what I mean with we need a robust workflow... we might want to consider creating automation for bumping the submodules whenever an update occurs, however if these files get changed but no new version is released, we still need to go down the manual path.

**Pull request closed without merging**
