### PR TITLE
Docsy update + Reenable RSS for blog index and navigation pages

### LINKED ISSUE #3740: RSS for website blog
- Reinstate RSS for the blog
- Context:
  - https://cloud-native.slack.com/archives/C02UN96HZH6/p1704185453199929
  - #3615

### PR DESCRIPTION
**Pull request by chalin**
- Fixes #3740
- **Preview**: 
  - https://deploy-preview-3780--opentelemetry.netlify.app/blog/
  - https://deploy-preview-3780--opentelemetry.netlify.app/blog/index.xml
  - https://deploy-preview-3780--opentelemetry.netlify.app/blog/page/4/

### CODE REVIEW

**Comment by chalin** [comment]
The link check is failing due to an issue with Docsy. I'll file an issue and report back here. Marking as DRAFT in the meantime.

**Comment by chalin** [comment]
FYI:

- https://github.com/google/docsy/issues/1785

**Review by svrnm — APPROVED** [review]
lgtm!

**Comment by chalin** [comment]
Thanks, I just noticed that the RSS button isn't showing up in blog section pages. Let me fix that.

**Comment by chalin** [comment]
Ok, the RSS-feed button is there where we need it now:

> image

Merging ✨

**Pull request merged**
