### PR TITLE
Scroll to the active item when the navbar is too long

### PR DESCRIPTION
**Pull request by rogerogers**
Scroll to the active item when the navbar is too long

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
Hi. Can you provide details (e.g., screenshots) of the problem this PR is trying to solve?

**Comment by rogerogers** [comment]
image
When clicking deep-level nav eg [Webengine](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/webengine/), the active nav item disappears, this pr scrolls it into view.
image

**Comment by rogerogers** [comment]
@chalin PTAL [Webengine](https://deploy-preview-2340--opentelemetry.netlify.app/docs/reference/specification/resource/semantic_conventions/webengine/)

**Comment by chalin** [comment]
Hi @rogerogers. Thanks for providing context and an example link. I'll get to this as soon as I can.

**Pull request merged**
