### PR TITLE
Generate favicon.ico and move favicon.png into subdir

### LINKED ISSUE #640: Docsy favicons are being used instead of that of OTel
The [Docsy favicons](https://github.com/google/docsy/tree/master/static/favicons), for example

> 

are currently being used by the website instead of the [OTel favicon](https://github.com/open-telemetry/opentelemetry.io/blob/acd8dc257a0c3e33dc1f9208301c76aa03700978/static/favicon.png):

>

### PR DESCRIPTION
**Pull request by breedx-splk**
Hopefully resolves #640.

According to [these docs](https://www.docsy.dev/docs/adding-content/iconsimages/#add-your-favicons) the theme favicons (docsy in our case) can be overwritten by placing them into the `static/favicons` subdir.

I didn't find any other references to the existing `favicon.png` so I moved it as well as adding the new `favicon.ico`.

### CODE REVIEW

**Comment by cartermp** [comment]
Unfortunately this seems to still render the docsy icon in the deploy preview

**Comment by breedx-splk** [comment]
> Unfortunately this seems to still render the docsy icon in the deploy preview

Yeah this is interesting. Chrome rendered the old one for me as well, even though the `favicon.ico` seems to be correct: https://deploy-preview-1590--opentelemetry.netlify.app/favicons/favicon.ico

Let me add the complete set of images and see how that goes.

**Review by cartermp — APPROVED** [review]
Yay! It does indeed work.

**Comment by chalin** [comment]
Coolio! Thanks @breedx-splk. I'm curious: how did you generate the different sizes of the favicon?

**Review by chalin — APPROVED** [review]

**Comment by breedx-splk** [comment]
> Coolio! Thanks @breedx-splk. I'm curious: how did you generate the different sizes of the favicon?

Well the [Docsy docs](https://www.docsy.dev/docs/adding-content/iconsimages/#add-your-favicons) say to use https://cthedot.de/icongen/, so I started with our high-res png that was already here and pushed it to icongen and got a zip file. That zip file didn't have every resolution, so I kept the ones that they generated and then used the imagemagick `convert` command to make the remaining missing sizes.

Make sense?

**Comment by chalin** [comment]
Yes, thanks for explaining the steps you took @breedx-splk!

**Pull request merged**
