### PR TITLE
Adding Checkly to OpenTelemetry Vendors

### PR DESCRIPTION
**Pull request by Dgiordano33**
We are requesting to add Checkly to the list of vendors that support the OpenTelemetry standard in the Vendor list here:

https://opentelemetry.io/ecosystem/vendors/

Checkly is a programmable monitoring platform that enables teams to configure their entire monitoring workflow from their IDE or terminal. Checkly also provide full-stack tracing via OpenTelemetry for any failures that occur in production, dramatically reducing MTTR.

### CODE REVIEW

**Comment by tiffany76** [comment]
Hi @Dgiordano33, could sign the CLA please? Thanks!

**Comment by Dgiordano33** [comment]
> Hi @Dgiordano33, could sign the CLA please? Thanks!

When I click the corporate link to apply I get an error:

"The Corporate CLA option is not enabled for this project. Please contact to your administrator to enable the Corporate CLA option for this project."

When I click the individual link, I get the same error. What should I sign?

Thank you so much for the help!

**Comment by svrnm** [comment]
@Dgiordano33 any updates on the CLA?

**Comment by cartermp** [comment]
Closing old PR

**Pull request closed without merging**
