### PR TITLE
Review visualizations for dark/light mode compatibility

### PR DESCRIPTION
**Pull request by SusanGithaigaN**
This pr resolves issue #5361 and adjusts the background color of the visualizations, ensuring they adapt to both light and dark modes. The overall color scheme and theme remain unchanged.

##Demo

[Review visualizations for dark_light mode compatibility #5361.webm](https://github.com/user-attachments/assets/2b6490c3-fe62-4b79-9e52-f29f2347aaee)

### CODE REVIEW

**Comment by SusanGithaigaN** [comment]
@chalin, @svrnm, I have implemented the changes you recommended.

**Comment by SusanGithaigaN** [comment]
> thanks, a few comments:
> 
> * the collector image has some text on it, which is almost invisible in dark mode: https://deploy-preview-5438--opentelemetry.netlify.app/docs/collector/ -- I suggest to drop that OTEL COLLECTOR and then crop the image to the visual elements
> * static/img/otel-diagram.svg has been fixed by @chalin's demonstration PR, if you update your branch to the latest changes of main I think there should be no difference remaining.
> * In a dedicated PR can you also take a look at the image on this page (in dark mode): https://deploy-preview-5438--opentelemetry.netlify.app/docs/concepts/instrumentation-scope/

@svrnm, I have implemented the changes you recommended.
I'm now working on the dedicated pr for the image on the instrumentation scope page.

**Review by svrnm — APPROVED** [review]

**Review by chalin — COMMENTED** [review]
Good changes here, thanks!

**Comment by SusanGithaigaN** [comment]
@chalin thank you
Can I create another pr for other registry related UI issues?

**Comment by chalin** [comment]
Hi @SusanGithaigaN - I'll let @svrnm respond (since he has been leading the Outreachy efforts) once he is back.

**Pull request merged**
