### PR TITLE
Delete superfluous imports and add quotation marks in getting-started.md

### PR DESCRIPTION
**Pull request by matthiasa4**

### CODE REVIEW

**Review by svrnm — APPROVED** [review]
looks good to me.

@open-telemetry/python-approvers PTAL

Preview: https://deploy-preview-2679--opentelemetry.netlify.app/docs/instrumentation/python/getting-started/

**Review by cartermp — APPROVED** [review]

**Comment by matthiasa4** [comment]
Thanks @svrnm & @cartermp - it looks like I won't be able to merge myself - is it ok if I leave updating the branch and merging to you?

**Comment by svrnm** [comment]
> Thanks @svrnm & @cartermp - it looks like I won't be able to merge myself - is it ok if I leave updating the branch and merging to you?

Yes, that's what we do as maintainers 😆 ... we wait a while for the @open-telemetry/javascript-approvers to give it a look and then we can merge it in

**Comment by matthiasa4** [comment]
Haha, fair point @svrnm - wasn't trying to rush it, just curious. First contribution in OpenTelemetry & first time I see the `code owners` feature being used which is quite cool! So all code is quadruple checked? (4 reviewers?)

**Comment by svrnm** [comment]
> Haha, fair point @svrnm - wasn't trying to rush it, just curious. First contribution in OpenTelemetry & first time I see the `code owners` feature being used which is quite cool! So all code is quadruple checked? (4 reviewers?)

No worries, I just wanted to manage expectations, happy to have you contribute :-) All code is checked by 2 parties: open-telemetry/docs-approvers and the maintainers/approvers of the individual sub-project (here open-telemetry/python-approvers). Technically there is only 1 approval required but we aim for having both parties to provide at least 1 approval. You can look into https://github.com/open-telemetry/opentelemetry.io/blob/main/.github/CODEOWNERS for more details

**Comment by svrnm** [comment]
thank you for your contribution @matthiasa4

**Comment by matthiasa4** [comment]
Thank you @svrnm - hope there is more to come :)

**Pull request merged**
