### PR TITLE
Try to really clarify that you need flask and wekzeug < 3

### PR DESCRIPTION
**Pull request by cartermp**
The evergreen problem that causes 50+ reply threads in slack persists. Herein I try to make it a little more clear what you need to do, until such a time that this resolves upstream.

### CODE REVIEW

**Review by TylerHelmuth — APPROVED** [review]

**Comment by cartermp** [comment]
I swear to fuckin god github actions

**Comment by rivToadd** [comment]
bless

**Review by svrnm — APPROVED** [review]

**Review by jaronoff97 — APPROVED** [review]

**Comment by cartermp** [comment]
Gonna merge this so we have all our bases covered on this limitation for now. Nothing about the guidance is changed, it's just added in more places.

**Comment by aabmass** [comment]
I'm a little confused, this should have been fixed in https://github.com/open-telemetry/opentelemetry-python-contrib/pull/2013

**Comment by cartermp** [comment]
Hrm. Is that released? When I follow the Getting Started guide on a fresh flask app (and I don't explicitly pin flask and werkzeug to <3) then I won't see traces, only logs.

**Comment by aabmass** [comment]
I think it should have been released. I'll look into it

**Comment by aabmass** [comment]
@cartermp, I was wrong it hasn't been released yet. The python maintainers are making a release this week. We can hopefully revert this PR after that's out.

**Comment by aabmass** [comment]
Hey @cartermp , the release just went out and I tested the getting started with flask 3 and it works. I think we can revert this PR and change the instructions:

```diff
-pip install 'flask<3' 'werkzeug<3'
pip install flask
```

**Comment by cartermp** [comment]
Awesome @aabmass -- I'll submit a PR and tag you on it

**Pull request merged**
