### PR TITLE
Added core collector receivers to registry

### PR DESCRIPTION
**Pull request by gramidt**
Added core collector receivers to registry

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
Oh, I'm actually not sure if that 'receiver' type is going to work with the type dropdown.

**Comment by austinlparker** [comment]
Yeah, looks like it doesn't show up. Maybe 'core'? You could also add a new type (look at how they're implemented in `layouts/registry/list.html`, you need a new lookup there and some css)

**Comment by gramidt** [comment]
Great catch, @austinlparker! Didn't serve the page this morning when starting. Dope...Need more coffee. Adding now.

**Comment by gramidt** [comment]
@austinlparker - Do you have a recommendation on the background color for types "receiver" and "processor"? I'll submit this via a different PR.

**Comment by austinlparker** [comment]
I don't really have any strong opinions. The text is white, so something that's readable with white text on it.

**Pull request merged**
