### PR TITLE
Adding TypeScript to "Getting Started"

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**
with reference to the closed PR #1800

### CODE REVIEW

**Comment by kaiwalyakoparkar** [comment]
@chalin @svrnm This seem to have not fixed the issue :/

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
> @chalin @svrnm This seem to have not fixed the issue :/

😡 ... 

have you signed the CLA before, e.g. for any other CNCF project?

**Comment by kaiwalyakoparkar** [comment]
I think yes, I have contributed to Kubernetes before. Is it possible for me to try sign it again. I looked it up but didn't find any way to sign it again. (Nor getting option to sign for the first time contributor)

**Comment by kaiwalyakoparkar** [comment]
I think I messed up the commit history. 
Update: Got reply from the ticket. Can be caused by no of commits. Will open a new pr from new branch

**Comment by cartermp** [comment]
> Can be caused by no of commits

Wow. Heh. Thanks for investigating. Fingers crossed!

**Pull request closed without merging**
