### PR TITLE
Add more concepts

### PR DESCRIPTION
**Pull request by flands**
- Merge docs and overview documentation into new data sources page
- Add a what is OpenTelemetry page
- Move common instrumentation documentation to new instrumenting page
- Add a data collection page

Also move collector introduction section of getting started guide to
main collector page.

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]
lgtm

**Comment by austinlparker** [comment]
g2g once the link checker is happy

**Comment by flands** [comment]
@austinlparker what am I missing? Appears to pass locally, but fails here -- log message is not helpful, but assume missing something..

**Comment by austinlparker** [comment]
`/content/en/about/_index.md` lines 40 and 41 refer to slugs that used to be at `/content/en/docs/_index.md`.

**Comment by flands** [comment]
Oh didn't look far enough up the log file -- thanks

**Pull request merged**
