### PR TITLE
Blog post: list of candidates for 2022 GC elections

### PR DESCRIPTION
**Pull request by jpkrohling**
Blog post announcing the list of candidates for the 2022 GC elections.

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
cc @bogdandrutu

**Review by austinlparker — APPROVED** [review]
lgtm w/suggested edits

**Comment by jpkrohling** [comment]
Suggestions accepted!

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
Now that this is merged it can be promoted - nothing else was in the pipeline so far, so I think we can promote however and whenever and wherever we like.

**Comment by chalin** [comment]
Would you like the homepage banner updated?

**Comment by chalin** [comment]
How about something like

> [Vote](https://opentelemetry.io/blog/2022/gc-elections-2022/) for OpenTelemetry Governance Committee [candidates](https://opentelemetry.io/blog/2022/gc-elections-2022-list-of-candidates/) starting October 18!

**Comment by chalin** [comment]
> It would be great to have the homepage banner updated and this blog post promoted as much as we can.

@jpkrohling - see #1864.

**Pull request merged**
