### PR TITLE
Update NGINX instrumentation versions.

### PR DESCRIPTION
**Pull request by fizzers123**
This Pull requests updates the versions of the NGINX instrumentation blog article. 
The new versions brings some very important bugfixes and features. 

[v1.0.1](https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/tag/webserver%2Fv1.0.1)

**- Bugfix: Correlation of traceparent propagation from Upstream to Downstream services in Nginx**

[webserver/v1.0.2](https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/tag/webserver%2Fv1.0.2)

- Support for Nginx stable version (1.22.0) and mainline versions(1.23.0, 1.23.1).
- Support for Nginx version (1.18.0) is deprecated and no longer supported from this release.

[webserver/v1.0.3](https://github.com/open-telemetry/opentelemetry-cpp-contrib/releases/tag/webserver%2Fv1.0.3)

- HTTP Data gatherer support for Nginx (https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/224 )
- Support for WebEngine Specification (https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/217 )
- Updated License to OpenTelemtery Authors (https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/233 )
- Bugfix for Nginx Error Reporting (https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/235 )
- Integration Tests were added (https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/227 )
- Other minor bug fixes

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
I think this is good for now, but ideally we'd want to point to another resource like a docs page or something else, so that we don't have to keep updating this post over time.

**Comment by chalin** [comment]
Hey @cartermp - I think that we shouldn't accept changes to old blog posts (and might want to consider reverting this one). For a discussion, see:

- #3493

**Comment by cartermp** [comment]
I'd prefer not to revert, at least for now. It's fine as a change lacking in policy. But I agree with the linked issue.

**Comment by chalin** [comment]
Yup, that works for me.

**Pull request merged**
