### PR TITLE
Add /fix:refcache action

### PR DESCRIPTION
**Pull request by cartermp**
Maybe, just maybe, this will let us just update the refcache in PR comments. Let's find out with https://www.gooddeals.com/

### CODE REVIEW

**Comment by cartermp** [comment]
God I hate computers sometimes

**Review by chalin — APPROVED** [review]
LGTM

I'm not sure that we can test an action like this in the PR that adds it.
Maybe just remove the seeded error and commit. We can test after that. WDYT?

**Comment by JamieDanielson** [comment]
@cartermp looks like this worked 🎉  (sorry if this is old news but I thought it was kinda cool anyway) Check out over here https://github.com/open-telemetry/opentelemetry.io/pull/3361#issuecomment-1755916347

**Comment by svrnm** [comment]
> @cartermp looks like this worked 🎉  (sorry if this is old news but I thought it was kinda cool anyway) Check out over here https://github.com/open-telemetry/opentelemetry.io/pull/3361#issuecomment-1755916347

I haven't used that action for a while assuming it's still broken so 🎉

**Pull request merged**
