### PR TITLE
Add BugSnag to the opentelemetry vendors list

### PR DESCRIPTION
**Pull request by AnastasiiaSvietlova**

### CODE REVIEW

**Comment by theletterf** [comment]
@AnastasiiaSvietlova Could you sign the CLA? Thanks!

**Comment by AnastasiiaSvietlova** [comment]
@theletterf I signed. Sorry for the delay. Will I get my copy of signed CLA?

**Comment by theletterf** [comment]
@AnastasiiaSvietlova Thank you! Yes, you can get a copy if you signed as an individual contributor. Otherwise, check with your organization.

**Review by theletterf — APPROVED** [review]

**Comment by AnastasiiaSvietlova** [comment]
Yes, as individual. How I can get it?

**Pull request merged**
