### PR TITLE
OTel Q&A Summary Blog Post - March 2023

### PR DESCRIPTION
**Pull request by avillela**
OTel Q&A summary blog post for March

---

**Preview**:

- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-02/
- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-01/

Redirect tests:

- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/end-user-q-and-a-series-otel-and-graphql/
- https://deploy-preview-2474--opentelemetry.netlify.app/blog/2023/otel-end-user-q-and-a-series-otel-and-graphql/

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
@cartermp et al. -- in terms of how the post filenames are suffixed (with -01, -02): originally the numbering was meant to match the month, since these are expected to be monthly posts. Should we make that consistent here too, or is numbering sequentially during the year good enough (as it is now in the PR)?

**Review by cartermp — APPROVED** [review]
This is such a good blog post. Love it.

**Comment by musingvirtual** [comment]
Hi there @cartermp @chalin 

I'd love to add the link to the OpenTelemetry in Practice event with Doug so folks know to attend it, and then push this live - 

https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=N3EzYWhjNzludnA0OXNoMDJxcG4yMTRibjUgZ29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBn&tmsrc=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com

What's the easiest way for me to do that? I know how to edit pull requests I'm an approver on but not quite sure how to edit other PRs without creating chaos haha.  Adriana is out of the office this week so she can't do it herself.  Thanks!

**Comment by avillela** [comment]
> @musingvirtual - so you'd like to add that link to the new post in this PR? Add it via a comment and suggestion, then one of us will take it from there.

@chalin I just pushed a commit with @musingvirtual's requested change (apologies for the delay...I was off last week)

**Review by cartermp — APPROVED** [review]

**Pull request merged**
