### PR TITLE
Rust registry updates

### PR DESCRIPTION
**Pull request by svrnm**
Updates & adds more rust elements to the registry

Preview: https://deploy-preview-3830--opentelemetry.netlify.app/ecosystem/registry/?language=rust

### CODE REVIEW

**Comment by cartermp** [comment]
more cspell funsies :)

**Review by theletterf — APPROVED** [review]

**Comment by svrnm** [comment]
Updated the PR to also contain `cargo add` instructions and links to the crates of each package

**Review by cartermp — APPROVED** [review]
Also looks good but there's some conflicts that need resolved that can't be done through GH's UI

**Comment by svrnm** [comment]
> Also looks good but there's some conflicts that need resolved that can't be done through GH's UI

resolved

**Pull request merged**
