### PR TITLE
add yottabyte in vendor list

### PR DESCRIPTION
**Pull request by vector1983**
add yottabyte in vendor list

### CODE REVIEW

**Comment by vector1983** [comment]
ok，it seems I need to sign CLA firstly， after I sign it ,is there anything else I need to do?

**Comment by svrnm** [comment]
> ok，it seems I need to sign CLA firstly， after I sign it ,is there anything else I need to do?

please sign the CLA first, we will then review your contribution and share additional feedback

**Comment by svrnm** [comment]
> > > ok，it seems I need to sign CLA firstly， after I sign it ,is there anything else I need to do?
> > 
> > 
> > please sign the CLA first, we will then review your contribution and share additional feedback
> 
> Thanks, I already signed the CLA.

After signing the CLA make sure that the email address you used in the PR is linked to the github account with which you committed (and signed) this PR. The message above (https://github.com/open-telemetry/opentelemetry.io/pull/5641#issuecomment-2487356152) will turn green when everything looks good

**Comment by vector1983** [comment]
ok, I did according to your advise, now it seems EasyCLA check passed, thanks.

**Comment by svrnm** [comment]
@vector1983 I see that the easyCLA check has passed, but the comment is still red (see screenshot). Would you mind closing this PR and raising a new one? TY

Bildschirmfoto 2024-11-20 um 14 03 21

**Pull request closed without merging**
