### PR TITLE
Libraries page

### PR DESCRIPTION
**Pull request by DIANAAJAMBO**
I added an image that compares native instrumentation and instrumentation libraries to enhance the explanation in the "Libraries" section.
I designed the image using figma and then added it to the images folder under "static" folder.
This was in relation to issue #5355

### CODE REVIEW

**Comment by svrnm** [comment]
@DIANAAJAMBO this PR still contains changes to the registry, can you double check?

**Comment by DIANAAJAMBO** [comment]
> @DIANAAJAMBO this PR still contains changes to the registry, can you double check?

@svrnm I made an error to work with the main branch from the start. So when i created a branch from my main, it came with all my past commits. I realize i should have kept one original branch without any commits and worked with the sub branches for both  contributions.

**Comment by DIANAAJAMBO** [comment]
> > > @DIANAAJAMBO this PR still contains changes to the registry, can you double check?
> > 
> > 
> > @svrnm I made an error to work with the main branch from the start. So when i created a branch from my main, it came with all my past commits. I realize i should have kept one original branch without any commits and worked with the sub branches for both contributions.
> 
> You still should be able to fix that, it's just some work. What I often do in such a situation is the following:
> 
> * Copy all changes you have done out of the repository folder, so that you have saved them
> * Reset your main branch to be in sync with upstream (open-telemetry/opentelemetry.io), github UI has some buttons for that where you can discard changes and get latest updates
> * Fetch those latest updates locally.
> * Create one new branch and add the files for your first PR, submit them
> * Go back to main branch
> * Create a second branch and add the files for your second PR, submit them
> 
> The habit you have to get into is having one branch per pull request, it's a learning curve but eventually it helps you to work on multiple things simultaneously.

This is very detailed. Thank you. Let me execute this.

**Comment by DIANAAJAMBO** [comment]
Hello @svrnm , I’ve successfully fixed the commit history, so there’s now a single commit reflecting the changes to the libraries page. Thank you for the advice, it was a huge help!

**Review by cartermp — APPROVED** [review]

**Review by chalin — COMMENTED** [review]
@DIANAAJAMBO: move the image added by this PR to `content/en/docs/concepts/instrumentation`.

**Pull request merged**
