### PR TITLE
collector: update internal logs config to include OTLP export

### LINKED ISSUE #5680: Add docs for updated collector internal telemetry features
**Desired feature or idea**

[This PR](https://github.com/open-telemetry/opentelemetry-collector/pull/10544) added features to directly send collector internal telemetry logs to an external provider. That feature is not yet added to the docs on the [internal telemetry page](https://opentelemetry.io/docs/collector/internal-telemetry/).

### PR DESCRIPTION
**Pull request by codeboten**
This adds the details to emit the Collector's internal logs via OTLP.

Fixes #5680

### CODE REVIEW

**Review by mowies — COMMENTED** [review]
i guess the table above with all the config options also needs some updating

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
@open-telemetry/collector-approvers PTAL

> i guess the table above with all the config options also needs some updating

Are those changes to the table relevant for this PR or are they independent? If they are related, can you tag the lines of code what needs to be changed, otherwise can you raise an issue with what needs to be changed? TY

**Comment by mowies** [comment]
Yes, the changes are relevant for this PR. New config options were added for the underlying feature and I think they should be reflected in the table as well. Probably just appended to the table here: https://github.com/open-telemetry/opentelemetry.io/pull/5702/files#diff-a03cac27414e8bfcdad01d15e4488809ea60503b6199040c78ef46d3f178f96dR88

**Review by djaglowski — APPROVED** [review]

**Comment by codeboten** [comment]
@mowies @svrnm if you're ok with this, i would like to file a separate issue to track this, as the options for exporting the collector's internal telemetry will need to be documented for metrics and traces as well.

**Comment by mowies** [comment]
sounds good :)

**Review by mowies — APPROVED** [review]

**Comment by svrnm** [comment]
> @mowies @svrnm if you're ok with this, i would like to file a separate issue to track this, as the options for exporting the collector's internal telemetry will need to be documented for metrics and traces as well.

works for me!

**Comment by codeboten** [comment]
opened https://github.com/open-telemetry/opentelemetry.io/issues/5721

**Pull request merged**
