### PR TITLE
Remove deprecated Go instrumentation libraries

### PR DESCRIPTION
**Pull request by pellared**
Remove Go packages that are no longer supported (deprecated) and removed since the latest release.

Fixes https://github.com/open-telemetry/opentelemetry-go-contrib/issues/4163

## Docs PR Checklist

- [x] This PR is for a documentation page whose authoritative copy is in the
      opentelemetry.io repository.

### CODE REVIEW

**Comment by pellared** [comment]
PTAL @open-telemetry/go-maintainers

**Comment by svrnm** [comment]
@pellared I am currently working on a larger PR towards the registry including this change, to avoid merge conflicts can we have it in one?

**Comment by pellared** [comment]
> @pellared I am currently working on a larger PR towards the registry including this change, to avoid merge conflicts can we have it in one?

LGTM

**Comment by svrnm** [comment]
see #3292

**Pull request closed without merging**
