### PR TITLE
Enable Prettier check over instrumentation/java

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #1063
- Enables format checking over `instrumentation/java` section
- Replaces one `relref` link by standard markdown link
- Tweaked two code blocks (changed from console to shell)

Preview: https://deploy-preview-2363--opentelemetry.netlify.app/docs/instrumentation/java/

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Review by mateuszrzeszutek — APPROVED** [review]

**Comment by chalin** [comment]
@cartermp @open-telemetry/javascript-maintainers - is this good to go?

**Comment by pichlermarc** [comment]
@chalin did you mean to ping `@open-telemetry/java-maintainers`? :slightly_smiling_face:

**Comment by chalin** [comment]
@pichlermarc - oops, yes, sorry!
Pinging @open-telemetry/java-maintainers!

**Comment by cartermp** [comment]
Yep, this should be good to go now.

**Comment by cartermp** [comment]
Also, maybe the JS team should be js-maintiners/js-approvers since this has happened a few times

**Pull request merged**
