### PR TITLE
Add github.com/thegeekyasian/go-chi-otel to registry

### PR DESCRIPTION
**Pull request by thegeekyasian**
Adding an adaption of OTEL for gochi/chi to the registry.

https://github.com/thegeekyasian/go-chi-otel

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
Okay, I will pull this in as the change in `main` that is breaking isn't related to this change.

**Comment by Isnor** [comment]
I don't think this should be included in the repository:

- The repository was an unattributed copy of [otel-chi](https://github.com/riandyrn/otelchi)
- I opened an issue in this repository, and the repository has since been deleted.

**Comment by svrnm** [comment]
thanks for letting us know @Isnor

**Pull request merged**
