### PR TITLE
Move languages under /docs/instrumentation

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #770

Preview:

- https://deploy-preview-963--opentelemetry.netlify.app/docs/instrumentation/
- Redirect tests (selected):
  - https://deploy-preview-963--opentelemetry.netlify.app/docs/go/
  - https://deploy-preview-963--opentelemetry.netlify.app/java/

### CODE REVIEW

**Comment by chalin** [comment]
@theletterf, @cartermp - any feedback on this simple reorg?

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
@tedsuo any thoughts/feedback as well?

**Comment by cartermp** [comment]
@chalin I dig it.

**Comment by austinlparker** [comment]
Aight, no further feedback so let's get this rolling

**Pull request merged**
