### PR TITLE
Add Ruby to SIG progress list

### PR DESCRIPTION
**Pull request by fbogsany**

### CODE REVIEW

**Comment by fbogsany** [comment]
@austinlparker I'm not sure what's up with CI for this. I *assume* I broke something, but I couldn't find a CI run for the previous PR #30

**Comment by austinlparker** [comment]
Yeah, looks like I've got a bug somewhere. Looking into it, stand by.

**Comment by austinlparker** [comment]
Bug is fixed in #50, but it'll need to merge first. You could probably take that change into your branch and push it then I can approve this?

**Comment by fbogsany** [comment]
@austinlparker thanks, that seems to have fixed it.

**Comment by austinlparker** [comment]
That fixed CI, but it looks like there's some bugs left in the chart logic, so let me take a stab at those.

**Comment by fbogsany** [comment]
I picked up that change as well.

**Comment by austinlparker** [comment]
Great! Thanks, this lgtm

**Pull request merged**
