### PR TITLE
Update semantic-conventions version to v1.26.0

### PR DESCRIPTION
**Pull request by opentelemetrybot**
Update semantic-conventions version to `v1.26.0`.

See https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.26.0.

### CODE REVIEW

**Comment by svrnm** [comment]
This needs some manual intervention since some of the links are giving a 403 meaning that there are blocks for the crawler

**Review by theletterf — APPROVED** [review]

**Comment by svrnm** [comment]
https://github.com/open-telemetry/semantic-conventions/pull/931 breaks some links in the docs, we need to address them first:

blog/2022/debug-otel-with-otel/index.html
  hash does not exist --- blog/2022/debug-otel-with-otel/index.html --> /docs/specs/semconv/http/http-spans/#common-attributes
docs/languages/java/automatic/configuration/index.html
  hash does not exist --- docs/languages/java/automatic/configuration/index.html --> /docs/specs/semconv/http/http-spans/#common-attributes
zh/docs/languages/java/automatic/configuration/index.html
  hash does not exist --- zh/docs/languages/java/automatic/configuration/index.html --> /docs/specs/semconv/http/http-spans/#common-attributes

**Review by lmolkova — APPROVED** [review]

**Pull request merged**
