### PR TITLE
Fix host metrics receiver link

### PR DESCRIPTION
**Pull request by austindrenski**

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
Have you signed the CLA?

**Comment by austindrenski** [comment]
> Have you signed the CLA?

Hmm, thought I had at some point, but appears not. Assuming its the CNCF one linked from [here](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/contribution-guidelines.md), then just signed a moment ago.

Off-topic, but wasn't there a bot at some point that would comment with a prompt to sign a required CLA?

**Comment by austinlparker** [comment]
Depending on how long ago you signed it, the CLA system changed to EasyCLA. It looks like it's stuck somehow though, can you close and re-open the PR to try and kick the check?

**Comment by austinlparker** [comment]
rad, thanks!

**Pull request merged**
