### PR TITLE
Add blog post for Distributed Tracing in Event Driven Architecture 

### PR DESCRIPTION
**Pull request by TamimiGitHub**

### CODE REVIEW

**Comment by TamimiGitHub** [comment]
Hey @chalin - we opened this PR instead. Thanks for helping out!

**Comment by chalin** [comment]
CLA is good now 👍

**Comment by TamimiGitHub** [comment]
I added another commit to fix some build issues with conventions - do I need to squash or can we squash on merge? And is there anything else on my side that needs to be done?

**Comment by austinlparker** [comment]
Hi, thanks for your contribution. I don't feel this content would be appropriate for our blog, due to the following:

- Heavily advertises a proprietary, non open source product (Solace)

Thanks.

**Pull request closed without merging**
