### PR TITLE
Add OpAMP spec

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #2795
- **Preview**: https://deploy-preview-2926--opentelemetry.netlify.app/docs/specs/opamp/

/cc @tigrannajaryan

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]
Thank you!

**Comment by chalin** [comment]
Thanks for the review @tigrannajaryan. I'm resolving link issues; it'll be good to go after that.

**Comment by svrnm** [comment]
@chalin can we make sure that the otel spec is always the first one? Right now OpAMP is listed before the otel spec

**Comment by chalin** [comment]
I'll address the spec order in a followup PR. Would that be ok @svrnm?

**Review by svrnm — APPROVED** [review]

**Comment by chalin** [comment]
@svrnm - FYI, will track the spec ordering change via:

- #2927

**Pull request merged**
