### PR TITLE
include more detail in the ToC on right side

### PR DESCRIPTION
**Pull request by zeitlinger**
Easier navigation:

image

### CODE REVIEW

**Review by svrnm — APPROVED** [review]
I am personally OK with this change, but I would like to get some more @open-telemetry/docs-maintainers to take a look

**Review by theletterf — APPROVED** [review]

**Comment by theletterf** [comment]
@zeitlinger Not opposed to this, but I'd consider splitting the docs to create a subsection just for Sprint Boot, given its popularity.

**Comment by svrnm** [comment]
> @zeitlinger Not opposed to this, but I'd consider splitting the docs to create a subsection just for Sprint Boot, given its popularity.

Yes, we should consider splitting this page, also it doesn't feel right to have "Spring Boot" under "Automatic", but let's move that into a dedicated discussion

**Review by mhausenblas — APPROVED** [review]

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
'gon merge now

**Pull request merged**
