### PR TITLE
Fix typo in Ops readme

### PR DESCRIPTION
**Pull request by davidamin**
* Fixes a small grammatical issue in the rhetorical question

### CODE REVIEW

**Review by chalin — APPROVED** [review]
Thanks! As soon as you sign the CLA we'll be able to merge.

**Comment by cartermp** [comment]
@davidamin Ping! Had a chance to take a look at the CLA?

**Comment by davidamin** [comment]
Yup! 🙂 Just waiting on approval from legal internally, should be able to get it all ready to go this week!

**Comment by davidamin** [comment]
Got the approval and got set up in EasyCLA, should be good to go now! Thanks all! 🙂

**Pull request merged**
