### PR TITLE
Add ItemNotFound  ItemListInternal feature flags to demo docs

### PR DESCRIPTION
**Pull request by klucsik**
Add docs to https://github.com/open-telemetry/opentelemetry-demo/pull/1382

### CODE REVIEW

**Comment by theletterf** [comment]
Related: https://github.com/open-telemetry/opentelemetry.io/pull/4005/files

**Comment by julianocosta89** [comment]
@klucsik I think we can close this one, right?

**Comment by svrnm** [comment]
the related PR got closed and not merged, I will close this PR, if this is not correct, feel free to reopen it

**Comment by klucsik** [comment]
Yeah, thank you, forgot to close this when we abandoned the other PR

**Pull request closed without merging**
