### PR TITLE
Replaced hipstershop to oteldemo

### LINKED ISSUE #3179: Demo code updates needed?
_Originally posted by @julianocosta89 in https://github.com/open-telemetry/opentelemetry.io/pull/3177#discussion_r1294758811_

> image

@julianocosta89, I'm noticing that `hipstershop.ShippingService` is used elsewhere in the demo code, maybe those need to be updated too?

### PR DESCRIPTION
**Pull request by julianocosta89**
Fix #3179.

The `hipstershop` name was removed from the demo some time ago, and the docs were not updated.
This PR syncs the docs with the changes done in the demo ShippingService(Rust) and FeatureFlagService(Elixir).

### CODE REVIEW

**Comment by julianocosta89** [comment]
How can I add `oteldemo` as a known word?

I'd like to avoid the following error:

`Warning: Unknown word (oteldemo)`

**Review by mviitane — APPROVED** [review]

**Review by chalin — APPROVED** [review]
LGTM once the spelling checker is happy.

**Comment by julianocosta89** [comment]
> 2\. npm run fix:dict

```
npm run fix:dict

> fix:dict
> find content layouts -name "*.md" -print0 | xargs -0 ./scripts/normalize-cspell-front-matter.pl

Can't locate JSON.pm in @INC (you may need to install the JSON module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.34.0 /usr/local/share/perl/5.34.0 /usr/lib/x86_64-linux-gnu/perl5/5.34 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.34 /usr/share/perl/5.34 /usr/local/lib/site_perl) at ./scripts/normalize-cspell-front-matter.pl line 5.
BEGIN failed--compilation aborted at ./scripts/normalize-cspell-front-matter.pl line 5.
```

**Comment by chalin** [comment]
I manually tweaked the page-local dictionaries, and all checks are passing now. I opened an issue for the problem you reported (thanks):

- #3187

**Pull request merged**
