### PR TITLE
Config LoadBalancer for frontendProxy

### PR DESCRIPTION
**Pull request by rcastley**
Environment:
OS: Multipass on Mac running Ubuntu 22.04 LTS
K8s: K3s v1.25.6+k3s1

Using `serviceType` yields the following error:

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
opentelemetry-demo:
- components.frontendProxy: Additional property serviceType is not allowed
```

Using the following in values file works:

```
components:
  frontendProxy:
    service:
      type: LoadBalancer
```

### CODE REVIEW

**Comment by cartermp** [comment]
Hello @rcastley, thanks for the PR. Can you sign the CLA? We can review then.

**Comment by rcastley** [comment]
Hi, just waiting upon approval from management at Splunk :-)

**Comment by cartermp** [comment]
@rcastley thanks! Unfortunately we churned the docs here and the file name is different. Would you like to still finish this up?

**Comment by chalin** [comment]
@rcastley - FYI, rebasing should be all you need to do to bring your PR up-to-date.

**Pull request closed without merging**
