### PR TITLE
Update semantic-conventions

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #2721
- Updates semantic-conventions under `/docs/specs/semconv` using the new organization brought in by https://github.com/open-telemetry/semantic-conventions/pull/166

> ~**IMPORTANT NOTE**: if this PR is merged, then the semantic-conventions will be **published to the production server**. Are y'all ok with that @jsuereth @joaopgrassi @open-telemetry/specs-semconv-approvers?~

**Preview**: https://deploy-preview-2982--opentelemetry.netlify.app/docs/specs/semconv/

### CODE REVIEW

**Comment by chalin** [comment]
FYI, I'm working on fixing links. Wanted to get the preview out ASAP.

**Review by jsuereth — APPROVED** [review]

**Comment by jsuereth** [comment]
If it helps, I had a few of my own link fixed here: https://github.com/jsuereth/opentelemetry.io/pull/new/wip-bump-semconv

**Review by cartermp — APPROVED** [review]

**Comment by chalin** [comment]
> https://github.com/jsuereth/opentelemetry.io/pull/new/wip-bump-semconv

All done, thanks!

**Comment by chalin** [comment]
Oh cool, you actually added custom frontmatter @jsuereth! Ok, let me use that too!

**Comment by chalin** [comment]
There will be followup PRs, but this is ready to go @jsuereth.
Do we need any more approvals, or can this be merged?

**Comment by chalin** [comment]
@jsuereth - if you agree to this being merged, please acknowledge that you've read the IMPORTANT NOTE in the opening comment, and agree with the semconv pages being published.

**Comment by chalin** [comment]
A few fixes that should land before the semconv pages are published:

- [ ] https://github.com/open-telemetry/semantic-conventions/pull/171
- [ ] https://github.com/open-telemetry/semantic-conventions/issues/172

**Review by joaopgrassi — APPROVED** [review]
Giving my approval on the general website structure for the semconv. Looks really nice!

**Review by svrnm — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]
Also wanted to comment, if you'd like to publish this now and add in a version *as soon as we have our first release*, I'm also ok with that timing.

**Comment by chalin** [comment]
> @chalin I'd like to actually only publish a stable tag ...

@jsuereth - Ok, here's what I've done: I've kept the `draft` status for the semconv pages. That means that they won't appear on the production server yet. That'll give us time to address the issues I've raised over the semconv repo.

Once the build is green, since this PR has your and other approvals, I'll merge.

**Comment by jsuereth** [comment]
Thanks for all the hard work @chalin !  This is really looking great!

**Pull request merged**
