### PR TITLE
[CI] Push back htmltest refcache expiry date, and fix a link

### PR DESCRIPTION
**Pull request by chalin**
I was refreshing cache entries, but I think that my IP might have been flagged by Cloudflare. So for now, I'll just push back the refcache expiry date. I managed to detect and fix one link.

### CODE REVIEW

**Comment by chalin** [comment]
Letting GH fix the refcache since my machine seems to have been blocked :-/

**Comment by chalin** [comment]
Got some updates over the refcache afer all \o/, so I force pushed those. Not sure why the refcache is being reported as stale?

**Review by svrnm — APPROVED** [review]

**Pull request merged**
