### PR TITLE
Update opentelemetry-specification version to 1.22.0

### PR DESCRIPTION
**Pull request by opentelemetrybot**
Update opentelemetry-specification version to `1.22.0`.

See https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.22.0.

### CODE REVIEW

**Review by svrnm — APPROVED** [review]
@chalin I'll leave it to you to merge this one

**Comment by chalin** [comment]
**Preview**: https://deploy-preview-2856--opentelemetry.netlify.app/docs/specs/otel/

**Review by chalin — APPROVED** [review]
Refcache updated. All checks are green now.

**Comment by chalin** [comment]
There are some adjustments to be made, but I'll submit those separately.

**Pull request merged**
