### PR TITLE
Add ITRS Geneos as vendor

### PR DESCRIPTION
**Pull request by jbarossitrs**
ITRS provides an Open Telemetry plugin that works with our Geneos product, see https://devdocs.itrsgroup.com/docs/geneos/data-collection/opentelemetry/current/opentelemetry.html

### CODE REVIEW

**Comment by jbarossitrs** [comment]
I'm not sure if the conversation in https://github.com/open-telemetry/opentelemetry.io/pull/2207 applies to ITRS, please let me know if there's anything more you need to know.

**Comment by svrnm** [comment]
@jbarossitrs please make sure that you sign the CLA

**Comment by jbarossitrs** [comment]
@svrnm I'm just waiting to hear from our legal department to confirm who our CLA Manager is and then I will sign the CLA.

**Comment by jbarossitrs** [comment]
I now have internal confirmation but have encountered a problem with easyCLA so waiting for a ticket with lxf to resolve https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-16896

**Comment by jbarossitrs** [comment]
@svrnm should all be resolved now I think

**Review by chalin — COMMENTED** [review]
I was going to offer to fix the formatting and refcache, but the PR has conflicts because the Vednors page was updated since this PR was created.

@svrnm @cartermp - I think we should switch to a data-driven approach for the vendors table so that we can avoid formatting issue, either as the part of #2178 or another issue. WDYT?

**Comment by chalin** [comment]
I thought that I might not be able to update the branch, but somewhat surprisingly I was.
Rebase done and checks fixed! 😅

**Comment by cartermp** [comment]
@chalin agreed.

**Pull request merged**
