### PR TITLE
Add Last9 to vendors list

### PR DESCRIPTION
**Pull request by prathamesh-sonpatki**

### CODE REVIEW

**Review by cartermp — COMMENTED** [review]
Hmmm, I'm not seeing a link to a distro of either an SDK or the collector in the docs for Last9. Can you show where that would be?

**Comment by prathamesh-sonpatki** [comment]
Thanks @cartermp Please check https://docs.last9.io/docs/integration-opentelemetry if that satisfies the requirement.

**Comment by cartermp** [comment]
That wouldn't cover requirements, no, since it's not a vendor distribution of the collector being used and the endpoint does not appear to support OTLP natively.

But it's an interesting point, because the Collector is designed to allow prometheus export, which the endpoint does appear to support. I'm not sure if that warrants inclusion. My gut feel is no, but curious what @chalin and @svrnm think.

**Comment by chalin** [comment]
My initial feeling was "no" as well, but we may need to discuss and clarify admission criteria.

**Comment by cartermp** [comment]
Yeah, I don't think we have any, heh

**Comment by svrnm** [comment]
> That wouldn't cover requirements, no, since it's not a vendor distribution of the collector being used and the endpoint does not appear to support OTLP natively.

TBH I am not sure if this applies to all the vendors we have in that list. We really need to fix that vendors page (and the integrators, adopters, etc.). I will try to find some time to come up with a suggestion

**Comment by cartermp** [comment]
I will say no to this for now, as it's not using OTLP.

**Pull request closed without merging**
