### PR TITLE
add GreptimeDB to vendor list

### PR DESCRIPTION
**Pull request by yuanbohan**

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by yuanbohan** [comment]
Hi @cartermp, Is there something needed to make this PR merged into main branch?

**Comment by yuanbohan** [comment]
Hi @cartermp, Is there something needed to make this PR merged into main branch?

**Comment by cartermp** [comment]
@yuanbohan you'll need to run `npm run fix` on your branch, and then I think it should all work?

**Comment by cartermp** [comment]
Agh, sorry.

For spelling, you'll need to add the vendor name here: https://github.com/open-telemetry/opentelemetry.io/blob/main/data/ecosystem/vendors.yaml#L1

For the refcache, you'll need to run:

`npm run test-and-fix`

**Comment by yuanbohan** [comment]
> Agh, sorry.
> 
> For spelling, you'll need to add the vendor name here: https://github.com/open-telemetry/opentelemetry.io/blob/main/data/ecosystem/vendors.yaml#L1
> 
> For the refcache, you'll need to run:
> 
> `npm run test-and-fix`

Thanks a lot. ❤️  Done.

**Comment by cartermp** [comment]
Thanks for the contribution!

**Pull request merged**
