### PR TITLE
chore: fix malfunctioning configuration file

### PR DESCRIPTION
**Pull request by TheJacobWalters**

### CODE REVIEW

**Comment by TheJacobWalters** [comment]
closes #2147

**Review by TylerHelmuth — APPROVED** [review]

**Review by cartermp — APPROVED** [review]
Ahh, good catch, thank you

**Comment by cartermp** [comment]
@TheJacobWalters if you'd like to get this merged feel free to move out of draft mode

**Comment by TheJacobWalters** [comment]
> @TheJacobWalters if you'd like to get this merged feel free to move out of draft mode

Ok, Ready for merge!

**Comment by svrnm** [comment]
thanks @TheJacobWalters

**Pull request merged**
