### PR TITLE
Update metrics spec status

### PR DESCRIPTION
**Pull request by reyang**
Update the metrics API spec status once https://github.com/open-telemetry/opentelemetry-specification/pull/1833 is merged.

### CODE REVIEW

**Review by weyert — APPROVED** [review]

**Review by mtwo — APPROVED** [review]

**Comment by mtwo** [comment]
open-telemetry/opentelemetry-specification#1833 was merged, so I am merging this

**Comment by alippai** [comment]
There is a typo: `freaze` vs `freeze`, also feature-freeze is not an official status yet (see the paragraph and linked page above).

**Comment by reyang** [comment]
@alippai I've submitted a fix #655.

**Comment by alippai** [comment]
Looks good to me. I didn't find that page before, thanks.

**Pull request merged**
