### PR TITLE
Update configuration.md

### PR DESCRIPTION
**Pull request by shalk**
update filter processor
ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/filterprocessor

### CODE REVIEW

**Comment by svrnm** [comment]
thanks @shalk!

@open-telemetry/collector-approvers PTAL

**Comment by svrnm** [comment]
@open-telemetry/collector-approvers PTAL!

**Review by songy23 — APPROVED** [review]
good catch!

**Review by svrnm — APPROVED** [review]

**Pull request merged**
