### PR TITLE
Solace instrumentation gi

### PR DESCRIPTION
**Pull request by isaacsgi**
Adding blog post for Solace corporation around Distributed Tracing in Event Driven Architecture with Solace PubSub+

### CODE REVIEW

**Comment by cartermp** [comment]
@isaacsgi could you sign the CLA? Then we can review. Thanks!

**Comment by isaacsgi** [comment]
> @isaacsgi could you sign the CLA? Then we can review. Thanks!

Working on it - I opened a [ticket ](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-19583) with Linux Foundation to determine who the CLA Manager is for my company.

**Comment by isaacsgi** [comment]
> > @isaacsgi could you sign the CLA? Then we can review. Thanks!
> 
> Working on it - I opened a [ticket ](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-19583) with Linux Foundation to determine who the CLA Manager is for my company.

OK - I was advised that I could do a person CLA, so I did that and it resolved one of them.  However, I don't get how to resolve the other as the commits certainly look like they are attached to my email address.  Any tips?

**Comment by chalin** [comment]
@isaacsgi - squashing didn't help. After pulling back this PR to your local machine, you might need to run the following and then force push:

```console
$ git commit --amend --no-edit --signoff
$ git push -f
```

**Review by chalin — CHANGES_REQUESTED** [review]
Rename all the image files to be all in lowercase, and use hyphens rather than underscores.

Actually, a simpler name for `Distributed_Tracing_graphics_slide.png` might just be `distributed-tracing.png`.

**Review by chalin — CHANGES_REQUESTED** [review]
This PR now includes changes to the semconv submodule, which we don't want:

> image

It might be simpler just to submit another PR and close this one. 🤷🏼‍♂️

**Comment by isaacsgi** [comment]
It seems like we keep getting stuck with the EasyCLA check.  Even when I select a personal one, it's not working.  Could it be blocked on the first time I did it where I created an [issue](https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-19583) w/the Linux Foundation for a Corporate CLA Check?

**Comment by TamimiGitHub** [comment]
Closing this PR. Opened a new one https://github.com/open-telemetry/opentelemetry.io/pull/3044

**Pull request closed without merging**
