### PR TITLE
Enable Prettier check over instrumentation/js

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #1063
- Enables format checking over `instrumentation/js` section
- Replaces `relref` link(s) by standard markdown link(s)
- Copyedits (minor)

⚠️ **Note**: code excerpts in code blocks also get reformatted per Prettier rules.

Preview: https://deploy-preview-2372--opentelemetry.netlify.app/docs/instrumentation/js/

### CODE REVIEW

**Review by cartermp — CHANGES_REQUESTED** [review]
uh oh. it looks like prettier is changing the quotes in the code blocks from double quotes to single quotes. The otel-js standard is to use single quotes.

**Comment by chalin** [comment]
Darn! Ok, will check tomorrow regarding options related to this, including not formatting the JS code excerpts. Anything else catch your eye, or was that it @cartermp?

**Comment by cartermp** [comment]
Nope, that's all!

**Comment by chalin** [comment]
Switching to single quotes, see:

- #2377

**Comment by chalin** [comment]
Rebased, and reformatted, using Prettier's single-quotes option. PTAL @cartermp

**Review by cartermp — APPROVED** [review]
Looks 'a gouda me

**Pull request merged**
