### PR TITLE
Bring java docs home

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #989
- There are no changes to the generated site files

Preview: https://deploy-preview-1002--opentelemetry.netlify.app/docs/instrumentation/java

/cc @cartermp

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Comment by chalin** [comment]
@trask - thanks for the review and approval! Is this good to merge or should we await for more approvals?

**Comment by trask** [comment]
I'd suggest waiting for an approval from a Java SDK maintainer (@anuraaga or @jkwatson)

**Review by anuraaga — APPROVED** [review]
I'm good with this and suspect any problems that crop up would be solvable with tooling

**Comment by chalin** [comment]
I just rebased and submitted one final fix for the GitHub repo links (like "View page source" -- note that the view and edit links won't work (they result in a 404) until this PR is merged).

Wishing y'all happy and restful holidays. I'm out until next year! ☃️

**Review by austinlparker — APPROVED** [review]

**Pull request merged**
