### PR TITLE
Update otel collector service name

### PR DESCRIPTION
**Pull request by rogercoll**
Open Telemetry collector service name changed from `otel-collector` to `otelcol`

### CODE REVIEW

**Comment by chalin** [comment]
Thanks for the PR @rogercoll. Is this meant to close #1126?

**Review by chalin — COMMENTED** [review]
RSLGTM

/assign @open-telemetry/collector-triagers 
/cc @open-telemetry/collector-contrib-approvers

**Review by jpkrohling — APPROVED** [review]
I didn't run the instructions, but I did compare this with the contents from the -releases repository. Did you run it yourself, @rogercoll?

**Comment by rogercoll** [comment]
@jpkrohling Yes, commands tested in Debian and Rpm based machines. 

The only commands that can cause confusion are the ones to install the packages as they are without the `sudo` command in front.

Would you add it?

**Review by chalin — APPROVED** [review]
Ok, thanks all!

**Comment by jpkrohling** [comment]
> Would you add it?

No, that's fine.

**Pull request merged**
