### PR TITLE
Add LogScale

### PR DESCRIPTION
**Pull request by ryanfaircloth**
Logscale now has a native OTLP (http) support

### CODE REVIEW

**Review by cartermp — CHANGES_REQUESTED** [review]
Looks like the formatting of the table got busted and logz.io is missing. Can you address that?

**Comment by ryanfaircloth** [comment]
> Looks like the formatting of the table got busted and logz.io is missing. Can you address that?

Sorry guess that's what I get for using the web editor instead of vscode I fixed it

**Review by chalin — APPROVED** [review]
👍

**Review by cartermp — APPROVED** [review]
Thanks!

**Pull request merged**
