### PR TITLE
otecol-data-flow-dashboard documentation

### PR DESCRIPTION
**Pull request by devrimdemiroz**
replacement for feature/otecol-data-flow-dashboard-PR797

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks!

For posterity, here's the discussion leading to the new PR: https://github.com/open-telemetry/opentelemetry.io/pull/2538#issuecomment-1492990286

**Comment by chalin** [comment]
Woohoo! Glad that this has landed. Thanks @devrimdemiroz! ✨

**Comment by devrimdemiroz** [comment]
> Woohoo! Glad that this has landed. Thanks @devrimdemiroz! ✨

@chalin Thank you for sharing your insights and recommendations in general and especially about the positioning of images in the document. After publishing, I have come to understand the validity of your perspective.

I am grateful for your patience and cooperation as we navigated this issue together.

Collaborating with someone as skilled and experienced as you is always a great experience. I appreciate your constructive feedbacks, which has undoubtedly contributed to the quality of the document.

**Comment by reyang** [comment]
@devrimdemiroz this is awesome! Thanks you!

**Pull request merged**
