### PR TITLE
GC 2023 Announcement Blog

### PR DESCRIPTION
**Pull request by dyladan**

### CODE REVIEW

**Comment by dyladan** [comment]
Link check fails because the link to the user profiles are fake. It is safe to ignore.

**Comment by dyladan** [comment]
Please merge Friday morning

**Comment by alolita** [comment]
+1 lgtm.

**Review by tedsuo — APPROVED** [review]

**Review by alolita — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
> Please merge Friday morning

Done, and public: https://opentelemetry.io/blog/2023/gc-election-results/

**Pull request merged**
