### PR TITLE
[CI/textlint] "Auto Config*" rewrite-rule capitalization fix

### PR DESCRIPTION
**Pull request by chalin**
- Completes the fix for #3891
- Fixes the "Auto Config*" rewrite-rule so that it forces the "c" in "config*" to be in lowercase
- Scrubs some page-local dictionaries

### CODE REVIEW

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
works for me, since this mainly affects java so far, would be good to hear if this makes sense?

**Review by theletterf — APPROVED** [review]

**Comment by chalin** [comment]
> works for me, since this mainly affects java so far, would be good to hear if this makes sense?

@svrnm - the rule is already present in the TextLint config, this PR is just a fix to the rule. So, ... is this good to merge?

**Comment by chalin** [comment]
> Would a sentence starting with Configure would be accepted with the new rule, for example:
> 
> > Configure this library in the following way:

@jeanbisutti - such an occurrence would not be affected by the rule.

**Comment by svrnm** [comment]
> > works for me, since this mainly affects java so far, would be good to hear if this makes sense?
> 
> @svrnm - the rule is already present in the TextLint config, this PR is just a fix to the rule. So, ... is this good to merge?

Yes :-)

**Pull request merged**
