### PR TITLE
Update blog archetype

### PR DESCRIPTION
**Pull request by svrnm**
Based on the previous few blog posts I suggest that we update the archetype to

* contain an example for the linked author name
* ask people to use prettier.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Review by chalin — APPROVED** [review]
All: I made some edits (for example to fix the author name syntax error). PTAL and let me know if you're ok with the changes. Otherwise, it LGTM!

**Comment by chalin** [comment]
@svrnm - could you test this updated archetype to ensure that it doesn't generate errors out-of-the-box?

**Comment by svrnm** [comment]
> @svrnm - could you test this updated archetype to ensure that it doesn't generate errors out-of-the-box?

tried it out, looked good to me, no errors.

**Review by chalin — APPROVED** [review]
Thanks!

**Pull request merged**
