### PR TITLE
add highlight.io to vendors

### PR DESCRIPTION
**Pull request by Vadman97**
Hi! Adding [highlight.io](https://app.highlight.io) per the [vendor docs](https://opentelemetry.io/ecosystem/vendors/#add-your-organization).

* Link to the documentation that details how your offering consumes OpenTelemetry natively via [OTLP](http://localhost:1313/docs/specs/otlp/).
    * Described in [detail on our docs](https://www.highlight.io/docs/general/company/open-source/contributing/adding-an-sdk).
* Link to your distribution, if applicable
    * https://app.highlight.io/
* Link that proves that your offering is open source, if applicable. An open source distribution does not qualify your offering to be marked “open source”.
    * [LICENSE](https://github.com/highlight/highlight/blob/3ecd5c367fe8830835cf6977788e8a5ac2b77257/LICENSE)
* GitHub handle or email address as a point of contact so that we can reach out in case we have questions
    * @jay-khatri
    * @vadman97
    * support@highlight.io

### CODE REVIEW

**Comment by cartermp** [comment]
@Vadman97 thanks for the contribution! Unfortunately it seems like our github action isn't committing changed files. In the interim, you can run `npm run check:links` and commit changes to the refcache yourself. Then we can go ahead and merge.

**Review by cartermp — APPROVED** [review]

**Comment by Vadman97** [comment]
thanks @cartermp ! updated, though I don't think I'm authorized to merge

**Comment by svrnm** [comment]
thanks @Vadman97

**Pull request merged**
