### PR TITLE
Simplify the display of the OTel starter TOC

### PR DESCRIPTION
**Pull request by jeanbisutti**

### CODE REVIEW

**Comment by jeanbisutti** [comment]
Before:

image


After:

image

**Comment by zeitlinger** [comment]
why remove the descriptions?

**Comment by jeanbisutti** [comment]
The descriptions were  very close to the titles. It seems redundant.

**Comment by zeitlinger** [comment]
> The descriptions were very close to the titles. It seems redundant.

how about improving the descriptions?

e.g. that out of the box means "included"

**Comment by jeanbisutti** [comment]
Perhaps we could remove the useless descriptions before working and discussing on useful ones?

**Review by zeitlinger — APPROVED** [review]

**Review by svrnm — APPROVED** [review]

**Pull request merged**
