### PR TITLE
Introduce version variables for erlang docs

### PR DESCRIPTION
**Pull request by svrnm**
Similar to what we have for Java & Collector already this pushes the versions used in erlang docs to the page front matter. This is only an intermediate step, in a further update we should have those taken from `data/`

### CODE REVIEW

**Review by chalin — CHANGES_REQUESTED** [review]
Nice, but let's keep this DRY.. The version params should exist in a single file: `content/en/docs/instrumentation/erlang/_index.md`. All files in the section will have access to the params via the `param` shortcode.

**Comment by svrnm** [comment]
> Nice, but let's keep this DRY.. The version params should exist in a single file: `content/en/docs/instrumentation/erlang/_index.md`. All files in the section will have access to the params via the `param` shortcode.

cool, I was wondering the same, I guess java is doing that and I somehow missed it

**Comment by svrnm** [comment]
@chalin fixed

**Review by ferd — APPROVED** [review]

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
Alright I did a fuckywucky with the refcache somehow in another PR, so the red in this PR is a false negative. I'm just going to merge it and then fix my mess up

**Pull request merged**
