### PR TITLE
Update banner for otel community day

### PR DESCRIPTION
**Pull request by cartermp**
kubecon's over, on to the next

(okay there's one more day left)

### CODE REVIEW

**Review by svrnm — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]
Good to me merged after 14:00 UTC

**Comment by steverao** [comment]
The submission time has expired, should we modify the content?

**Comment by cartermp** [comment]
Yeah, we should. I'll get something up there for the general event.

**Comment by cartermp** [comment]
Yeah, we should. I'll get something up there for the general event.

**Pull request merged**
