### PR TITLE
Add Observe, Inc. to the vender list.

### PR DESCRIPTION
**Pull request by NathanNam**

### CODE REVIEW

**Comment by svrnm** [comment]
@NathanNam please sign the CLA so we can proceed reviewing it

**Review by cartermp — APPROVED** [review]
LGTM; we'd prefer docs links if you got them over a blog post, but this certainly meets the requirements.

**Comment by NathanNam** [comment]
> LGTM; we'd prefer docs links if you got them over a blog post, but this certainly meets the requirements.

Changed the link to the documentation page (https://docs.observeinc.com/en/latest/content/integrations/otel/opentelemetry.html).

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
> > LGTM; we'd prefer docs links if you got them over a blog post, but this certainly meets the requirements.
> 
> Changed the link to the documentation page (https://docs.observeinc.com/en/latest/content/integrations/otel/opentelemetry.html).

When you add URLs you need to run `npm run test` to get the refcache updated accordingly.

**Comment by NathanNam** [comment]
> > > LGTM; we'd prefer docs links if you got them over a blog post, but this certainly meets the requirements.
> > 
> > 
> > Changed the link to the documentation page (https://docs.observeinc.com/en/latest/content/integrations/otel/opentelemetry.html).
> 
> When you add URLs you need to run `npm run test` to get the refcache updated accordingly.

When I ran ``npm run test``, I got the following error. I'm not sure whether these errors were caused by changes I made on ``vendors.md``.

```
Start building sites …
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended darwin/arm64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
ERROR 2023/05/15 09:20:42 render of "page" failed: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/layouts/_default/baseof.html:19:7": execute of template failed: template: _default/single.html:19:7: executing "_default/single.html" at <partialCached "scripts.html" .>: error calling partialCached: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR 2023/05/15 09:20:42 render of "page" failed: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/blog/baseof.html:33:7": execute of template failed: template: blog/single.html:33:7: executing "blog/single.html" at <partial "scripts.html" .>: error calling partial: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR 2023/05/15 09:20:42 render of "page" failed: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/blog/baseof.html:33:7": execute of template failed: template: blog/single.html:33:7: executing "blog/single.html" at <partial "scripts.html" .>: error calling partial: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR 2023/05/15 09:20:42 render of "page" failed: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/blog/baseof.html:33:7": execute of template failed: template: blog/single.html:33:7: executing "blog/single.html" at <partial "scripts.html" .>: error calling partial: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR 2023/05/15 09:20:42 failed to render pages: render of "page" failed: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/layouts/_default/baseof.html:19:7": execute of template failed: template: _default/search.html:19:7: executing "_default/search.html" at <partialCached "scripts.html" .>: error calling partialCached: "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/layouts/partials/scripts.html:84:30": execute of template failed: template: partials/scripts.html:84:30: executing "partials/scripts.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): "/Users/nathan.nam/Documents/GitHub/NathanNam/opentelemetry.io/themes/docsy/assets/scss/main.scss:1:1": File to import not found or unreadable: ../vendor/bootstrap/scss/functions.
Total in 1298 ms
ERROR: "check:links" exited with 255.
```

**Comment by chalin** [comment]
Hi. I get the impression that you might not have run `npm install`? For setup details, see https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md#local-setup. Only after can you run the test script.

**Comment by NathanNam** [comment]
> Hi. I get the impression that you might not have run `npm install`? For setup details, see https://github.com/open-telemetry/opentelemetry.io/blob/main/CONTRIBUTING.md#local-setup. Only after can you run the test script.

`npm install` -> `npm run test` solved my issue. Thank you all!

**Pull request merged**
