### PR TITLE
Update docker-deployment.md

### PR DESCRIPTION
**Pull request by CharlieTLe**
Optimizations on trace-based testing in https://github.com/open-telemetry/opentelemetry-demo/pull/1659 changed how tracetest is enabled. This change updates the documentation to reflect on enabling trace based tests should be done.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Overall lgtm, @open-telemetry/demo-approvers PTAL!

**Comment by tiffany76** [comment]
Hi @open-telemetry/demo-approvers, does anyone have time to give this a look? Thanks!

**Comment by julianocosta89** [comment]
I'm confused.
Wasn't that already updated in https://github.com/open-telemetry/opentelemetry.io/pull/5215?

**Comment by svrnm** [comment]
> I'm confused. Wasn't that already updated in #5215?

Indeed, merging main into this PR seems to not lead to a conflict.

@CharlieTLe apologies, we were not aware that there have been 2 PRs trying to accomplish the same thing, we appreciate your contribution nevertheless.

**Pull request closed without merging**
