### PR TITLE
Update OTel spec submodule to include the 1.20.0 schema.

### PR DESCRIPTION
**Pull request by carlosalberto**
See:

- https://github.com/open-telemetry/opentelemetry-specification/pull/3364

**Preview**:

- https://deploy-preview-2584--opentelemetry.netlify.app/docs/reference/specification/
- https://deploy-preview-2584--opentelemetry.netlify.app/docs/reference/specification/status/

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
Looks like there's some error in the documents that make the site unable to build.

**Comment by chalin** [comment]
> Looks like there's some error in the documents that make the site unable to build.

Yeah, we're probably hitting #2478. I'm on it.

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
Build and checks are green!

**Comment by carlosalberto** [comment]
Thanks so much for figuring this out!

**Pull request merged**
