### PR TITLE
Update spring-boot.md

### PR DESCRIPTION
**Pull request by XiaotianZha**
Without `<scope>import</scope>`， there will be an error 
 Could not find artifact io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter:jar:unknown

### CODE REVIEW

**Comment by cartermp** [comment]
@open-telemetry/javascript-approvers PTAL!

**Comment by JamieDanielson** [comment]
@open-telemetry/java-approvers

**Comment by cartermp** [comment]
literally happens every work, god dammit

**Review by jeanbisutti — APPROVED** [review]

**Review by trask — APPROVED** [review]

**Comment by svrnm** [comment]
thank you @XiaotianZha !

**Comment by XiaotianZha** [comment]
> thank you @XiaotianZha !

You are welcom! It's my first PR for open source project, It's means a lot to me!

**Comment by svrnm** [comment]
@XiaotianZha Awesome, congratulations then to your first PR to an OSS project, and thank you for picking our project. Keep up the good work!

**Pull request merged**
