### PR TITLE
Update what-is-opentelemetry.md

### PR DESCRIPTION
**Pull request by Rick-Anderson**
A bulleted list is easier to read and less words. Less is more. Crucially, I removed Crucially as it's Crucially wordy. Consider **bold** for emphasis.

148 words v. 106 words. Less is more.

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
Less is indeed more. Thanks, Rick!

**Comment by Rick-Anderson** [comment]
@theletterf thanks for  accepting my PR. Now that I know my edit PR's will be considered, I'll try to submit more.

**Comment by svrnm** [comment]
thanks for your contribution @Rick-Anderson and for considering to do more! 🎉

**Pull request merged**
