### PR TITLE
[ja] add translation of the index page of collector

### PR DESCRIPTION
**Pull request by ymotongpoo**
## Docs PR Checklist

- [X] This PR is for a documentation page whose authoritative copy is in the
      opentelemetry.io repository.

### CODE REVIEW

**Comment by chalin** [comment]
@open-telemetry/docs-maintainers et al. - I suggest that we hold back on merging this PR until I've addressed:

- #4825

We could just patch things for this PR (by adding the `ja` page path to the appropriate script), but I'd rather take a little extra time to fix this for all localizations.

**Review by chalin — APPROVED** [review]
Unblocking -- for details, see https://github.com/open-telemetry/opentelemetry.io/issues/4825#issuecomment-2226547076. /cc @svrnm 

Also, this LGTM.

**Comment by ymotongpoo** [comment]
@katzchang yoroshiku desu

**Review by katzchang — APPROVED** [review]
Approved🍝

**Pull request merged**
