### PR TITLE
Add Typescript to "libraries" js doc

### LINKED ISSUE #1829: Add Typescript to "libraries" js doc
Doc: https://opentelemetry.io/docs/instrumentation/js/libraries/

Child of https://github.com/open-telemetry/opentelemetry.io/issues/1772

### PR DESCRIPTION
**Pull request by amanksingh99**
closes #1829

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Changes LGTM. @open-telemetry/javascript-approvers PTAL!

**Review by legendecas — APPROVED** [review]

**Review by dyladan — APPROVED** [review]
I guess @chalin wants you to use tabs differently but the content looks good to me

**Comment by chalin** [comment]
> I guess @chalin wants you to use tabs differently but the content looks good to me

Actually, if you are satisfied, then this can go is as is.

**Review by chalin — CHANGES_REQUESTED** [review]
I'm ok if this goes in as is, with the local OTel "tabs".

**Note that you'll need to rebase and prefix your `tab` shortcode names with `ot-`, like this**: `tabs` becomes `ot-tabs`. Otherwise the PR will fail after it is merged.

After you make these changes I'll give the PR a final approval. Thanks, and sorry for the commotion!

**Review by chalin — APPROVED** [review]
Thanks @amanksingh99 for the content. Thanks all for the reviews. I've made the shortcode updates, and all is good now. LGTM too now!

**Pull request merged**
