### PR TITLE
Refresh Java docs

### PR DESCRIPTION
**Pull request by chalin**
Bringing in https://github.com/open-telemetry/opentelemetry-java-docs/pull/8

Preview:  https://deploy-preview-998--opentelemetry.netlify.app/docs/instrumentation/java/

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
I like it!

**Comment by cartermp** [comment]
Looks like this also incorporates https://github.com/open-telemetry/opentelemetry.io/issues/997

I think it looks fine, though I'd be interested in others' opinions

**Comment by chalin** [comment]
> Looks like this also incorporates #997

No, #997 isn't a part of this PR. That change will need to land in the java-docs repo first.

**Comment by cartermp** [comment]
Aha, my bad, yes. It was the link titles that got adjusted.

**Comment by chalin** [comment]
Right.

**Pull request merged**
