### PR TITLE
Add exporters & instrumentation for otel-cpp to registry.

### PR DESCRIPTION
**Pull request by lalitb**
Preview: https://deploy-preview-892--opentelemetry.netlify.app/registry/?s=&component=all&language=cpp#

### CODE REVIEW

**Review by chalin — CHANGES_REQUESTED** [review]
The `language` field value should be `cpp`, per https://github.com/open-telemetry/opentelemetry.io/blob/fa565becf57517b45517cb3687e5b48da243af05/layouts/registry/list.html#L6

Otherwise, these entries don't show up in the registry as you can see this PR's preview https://deploy-preview-892--opentelemetry.netlify.app/registry/?s=&component=all&language=cpp#

**Comment by chalin** [comment]
Let me know if you'd like me to make the changes @lalitb.

**Comment by lalitb** [comment]
> Let me know if you'd like me to make the changes @lalitb.

Thanks @chalin if you can do so, else I will take it during my morning.

**Comment by chalin** [comment]
> Thanks @chalin if you can do so, else I will take it during my morning.

I'm on it.

**Comment by chalin** [comment]
Use `cpp` for the language field

**Comment by chalin** [comment]
```diff
diff --git a/content/en/registry/exporter-cpp-zipkin.md b/content/en/registry/exporter-cpp-zipkin.md
--- content/en/registry/exporter-cpp-zipkin.md
+++ content/en/registry/exporter-cpp-zipkin.md
@@ -1,9 +1,9 @@
 ---
 title: Zipkin Exporter
 registryType: exporter
 isThirdParty: false
-language: c++
+language: cpp
 tags:
   - c++
   - exporter
 repo: https://github.com/open-telemetry/opentelemetry-cpp/tree/main/exporters/zipkin
diff --git a/content/en/registry/instrumentation-cpp-httpd.md b/content/en/registry/instrumentation-cpp-httpd.md
--- content/en/registry/instrumentation-cpp-httpd.md
+++ content/en/registry/instrumentation-cpp-httpd.md
@@ -1,9 +1,9 @@
 ---
 title: httpd(Apache) Instrumentation
 registryType: instrumentation
 isThirdParty: true
-language: c++
+language: cpp
 tags:
   - c++
   - instrumentation
 repo: https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/httpd
diff --git a/content/en/registry/instrumentation-cpp-nginx.md b/content/en/registry/instrumentation-cpp-nginx.md
--- content/en/registry/instrumentation-cpp-nginx.md
+++ content/en/registry/instrumentation-cpp-nginx.md
@@ -1,9 +1,9 @@
 ---
 title: Nginx Instrumentation
 registryType: instrumentation
 isThirdParty: true
-language: c++
+language: cpp
 tags:
   - c++
   - instrumentation
 repo: https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation/nginx

```

**Comment by chalin** [comment]
Apologies for the extra comments that have appeared: I was trying to edit the PR via github.dev, but it wouldn't let me commit the changes, so I fall back to editing each file individually (the only way I could get the changes in without submitting a new PR).

**Review by chalin — APPROVED** [review]
Language fields updated

**Pull request merged**
