### PR TITLE
fix deprecated semantic-conventions

### PR DESCRIPTION
**Pull request by yukimotochern**

### CODE REVIEW

**Comment by cartermp** [comment]
@yukimotochern for this as well, once the CLA is signed we can review.

**Comment by svrnm** [comment]
@open-telemetry/javascript-approvers PTAL

**Review by maryliag — APPROVED** [review]

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
@yukimotochern thank you for your contribution!

**Comment by yukimotochern** [comment]
> @yukimotochern thank you for your contribution!

No problem!

**Pull request merged**
