### PR TITLE
Spotlight project integrations

### PR DESCRIPTION
**Pull request by cartersocha**
I wanted to put our integrations front and center for new users. Hopefully this will drive more users to our integrations and encourage more vendors to produce OTel integrations or add existing integrations to our website.

### CODE REVIEW

**Comment by svrnm** [comment]
Preview: https://deploy-preview-3306--opentelemetry.netlify.app/

Screenshot 2023-09-21 at 20 28 07

**Comment by svrnm** [comment]
> I wanted to put our integrations front and center for new users. Hopefully this will drive more users to our integrations and encourage more vendors to produce OTel integrations or add existing integrations to our website.

I agree with the reasoning, but the position / wording seems off, since both other boxes are short calls to action ("Learn!", "Try!"), is there a way to express in 2-4 words what people should be doing here?

**Comment by cartersocha** [comment]
Haha I was struggling a bit with that myself @svrnm. Maybe “Explore project integrations”? Open to any suggestions

**Comment by cartermp** [comment]
Maybe just `Explore Integrations`?

**Comment by cartersocha** [comment]
Updated

**Review by cartermp — APPROVED** [review]
I dig it.

**Review by svrnm — APPROVED** [review]
🥳

**Pull request merged**
