### PR TITLE
Update/rust example hyper v1

### PR DESCRIPTION
**Pull request by ekquasar**
Supersedes PR#4236

# Summary
The HTTP crate hyper has had a major version update (from 0.14 to 1.x; more details at https://hyper.rs/guides/1/upgrading/).

In this PR, I've updated the roll_dice Rust example to use the new major version.

Moreover, the opentelemetry packaging has changed (esp. the refractor of the sdk from the core opentelemetry base crate into its own opentelemetry_sdk). I've updated the example accordingly.

### CODE REVIEW

**Comment by hdost** [comment]
I would wait until https://github.com/open-telemetry/opentelemetry-rust/issues/1427 is resolved.

**Comment by svrnm** [comment]
> I would wait until [open-telemetry/opentelemetry-rust#1427](https://github.com/open-telemetry/opentelemetry-rust/issues/1427) is resolved.

I blocked the issue, please update us when we can unblock it

**Comment by ekquasar** [comment]
I'm sorry, @hdost , I read that -http thread and it's not clear to me why it's beneficial to wait until other packages update to hyper 1.0? Is it just that e.g. a new dev would follow the example (e.g. this updated one) with hyper 1.x and then try to use the -http exporter which would then barf?

**Comment by svrnm** [comment]
@hdost @ekquasar any updates?

**Comment by ekquasar** [comment]
The desire appears to be to "step across the line together" with other projects. I wouldn't advocate that approach, but I understand there may be good reasons to do so.

**Comment by ekquasar** [comment]
It's a community question, perhaps for the maintainers, not a technical one; to my understanding.

**Comment by svrnm** [comment]
@open-telemetry/rust-approvers is there anything we can do for this PR?

**Comment by svrnm** [comment]
@open-telemetry/rust-approvers following up, anything we can do for this PR? Close it or instructions for @ekquasar how to get this merged?

**Comment by svrnm** [comment]
@open-telemetry/rust-approvers can you take a look, if we can unblock this PR now? https://github.com/open-telemetry/opentelemetry-rust/issues/1427 is closed now, so please check once again

**Comment by cartermp** [comment]
Closing out old PR

**Pull request closed without merging**
