### PR TITLE
Update trace-receiver.md #1501

### PR DESCRIPTION
**Pull request by rahuldimri**
Added below line:
In reference of https://github.com/open-telemetry/opentelemetry.io/pull/1501/files
> - execute `go mod tidy` to add module `github.com/rquedas/otel4devs/collector/receiver/trace-receiver/tailtracer` to go.mod
> - execute `go build` to re-compile packages and dependencies

### CODE REVIEW

**Review by cartermp — DISMISSED** [review]
I think the updates are fine, but would like @rquedas to sign off on this as well.

**Review by chalin — CHANGES_REQUESTED** [review]
Can you explain _why_ you are making this change? That would help us better understand what you are trying to achieve.

I don't think that your addition is inline with the original intent of the **Check your work** callouts.

**Comment by rahuldimri** [comment]
This is in reference of the PR request https://github.com/open-telemetry/opentelemetry.io/pull/1501/files which were in queue and didn't passed due to check fail.

execute go mod tidy to add module github.com/rquedas/otel4devs/collector/receiver/trace-receiver/tailtracer to go.mod
execute go build to re-compile packages and dependencies

**Comment by rquedas** [comment]
@rahuldimri, you may have noticed that the check your work sections are meant to explain code implementation and changes and not go commands.
The tutorial is written based on the assumption that the component developer already knows how to interact with go commands.

@chalin and @cartermp, do you feel the same about the current implementation?

**Comment by chalin** [comment]
Based on @rquedas's comments, I've vote against the changes proposed in this PR. (I'm still opening to hearing more about the reason behind the change, as I commented earlier.)

**Comment by svrnm** [comment]
As discussed we are not going to merge this PR.

@rahuldimri thank you for your contribution and apologies for declining it.

**Pull request closed without merging**
