### PR TITLE
Update trace-receiver.md

### PR DESCRIPTION
**Pull request by noahdyp**
1. Need to assign -p 14250:14250 otherwise connect Jaeger will be failed
2. It is necessary to rebuild when you modify components.go to supporting custom Receiver

### CODE REVIEW

**Comment by svrnm** [comment]
@rquedas can you look at the suggested changes.

@noahdyp please make sure that you sign the CLA successfully, if you're a corporate contributor work with your internal OSS experts to get it signed, otherwise you can go with "individual contributor"

**Comment by rahuldimri** [comment]
Are we still working on this ?.

**Comment by cartermp** [comment]
@rahuldimri if you're interested in taking up this work, please feel free to submit another PR (that links to this one and gives credit) -- we can close this one due to inactivity in favor of yours if you do so.

**Comment by rquedas** [comment]
@rahuldimri "It is necessary to rebuild when you modify components.go to supporting custom Receiver" in the context of the tutorial, you are in development mode, so building your code to see the change is implicit, not sure if we need to call it out.

@austinlparker  and @svrnm, what do you think

**Comment by rahuldimri** [comment]
Sure thanks let me have a look into this.

**Comment by cartermp** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry.io/pull/1598

**Pull request closed without merging**
