### PR TITLE
Add SigNoz in the vendor list

### PR DESCRIPTION
**Pull request by pranay01**
I am not very clear on what does `Distribution` field mean. I have kept it as `Yes` as product similar to ours has this as `Yes`. 
Please advise on what does it mean and if our entry should be changed

### CODE REVIEW

**Comment by cartermp** [comment]
I've interpreted "distribution" to mean having built SDK distributions or a collector distribution (but readily acknowledge some entries on the list could be inaccurate with respect to this).

**Comment by pranay01** [comment]
Got it. We have added functionalities on top of opentelemetry, like exporters and processors - https://github.com/SigNoz/opentelemetry-collector-contrib

So, I think `Yes` for "distribution" should be accurate.

**Comment by cartermp** [comment]
Sounds good!

**Review by cartermp — APPROVED** [review]

**Review by svrnm — APPROVED** [review]
lgtm

**Review by austinlparker — APPROVED** [review]

**Pull request merged**
