### PR TITLE
[wip] - Update ruby docs to latest

### PR DESCRIPTION
**Pull request by cartermp**
Pulls in some improvements and a new article on configuring instrumentation libs

### CODE REVIEW

**Comment by cartermp** [comment]
PR that fixes the build: https://github.com/open-telemetry/opentelemetry-ruby/pull/1081

**Comment by cartermp** [comment]
Weird, so I can actually run `npm run serve` on this branch and the site builds and is browsable with the new content. I guess it's to do with the rest here: https://github.com/open-telemetry/opentelemetry-ruby/issues/1104

**Comment by chalin** [comment]
To check links run `npm run check-links`.

**Comment by chalin** [comment]
We'll want to wait for https://github.com/open-telemetry/opentelemetry-ruby/pull/1120 before updating and merging this PR.

**Comment by chalin** [comment]
- Superseded by #1099

**Pull request closed without merging**
