### PR TITLE
Wrap .NET docs to 80 chars

### PR DESCRIPTION
**Pull request by cartermp**
Draft for now, might want to wait for https://github.com/open-telemetry/opentelemetry.io/pull/1041 to be merged first

### CODE REVIEW

**Comment by chalin** [comment]
PR #1041 has been merged. There are now conflicts with this PR. I'm glad to submit an updated PR if you'd like. Let me know @cartermp what you prefer.

**Comment by cartermp** [comment]
@chalin I'll get this one over the finish line. Conflicts done, just want to re-run the tool on the relevant docs.

**Comment by cartermp** [comment]
@chalin all done now!

**Comment by chalin** [comment]
\o/

**Review by chalin — APPROVED** [review]

**Pull request merged**
