### PR TITLE
Vendor page: AppDynamics link update

### PR DESCRIPTION
**Pull request by mhosabettu**
Hi,

I have updated the URL to https://docs.appdynamics.com/latest/en/application-monitoring/appdynamics-for-opentelemetry on the vendors page

### CODE REVIEW

**Review by chalin — CHANGES_REQUESTED** [review]
Thanks for updating the link, but while the change seems reasonable, the link redirects to version 22.4 and results in a 404:

> 

It seems like the page has moved to: https://docs.appdynamics.com/22.4/en/appdynamics-for-opentelemetry

Please make the necessary adjustments. Thanks

**Comment by mhosabettu** [comment]
Thank you Charlin! Let me talk to the team and fix this!

**Comment by mhosabettu** [comment]
Hello Charlin,
The internal problem is fixed. https://docs.appdynamics.com/latest/en/application-monitoring/appdynamics-for-opentelemetry is working now!

**Review by chalin — APPROVED** [review]
I'm glad that you got that fixed.
LGTM

**Comment by chalin** [comment]
Thanks for having submitted this PR ✨

**Comment by mhosabettu** [comment]
Thank you for merging!

**Pull request merged**
