### PR TITLE
Blog Go Web-apps repackaging and copyedits

### PR DESCRIPTION
**Pull request by chalin**
- Followup to #1581 

Preview: https://deploy-preview-1646--opentelemetry.netlify.app/blog/2022/go-web-app-instrumentation/

- [x] Create page bundle with local & compressed images
- [x] Get approval from @NavehMevorach @svrnm @cartermp 
- [ ] Remove draft status

### CODE REVIEW

**Comment by chalin** [comment]
This is ready for review @NavehMevorach @svrnm @cartermp. 

I won't have time to make a full pass for copyediting, but this article is fine to publish as is.

**Review by cartermp — APPROVED** [review]

**Review by NavehMevorach — APPROVED** [review]

**Comment by chalin** [comment]
@svrnm - is this good to go?

**Review by svrnm — APPROVED** [review]
lgtm

**Review by chalin — COMMENTED** [review]
Thanks all!

**Pull request merged**
