### PR TITLE
Fix typo in WebTracer notes

### PR DESCRIPTION
**Pull request by aknot242**

### CODE REVIEW

**Comment by cartermp** [comment]
@aknot242 thanks! Can you sign the CLA? Then we can review -> merge.

**Comment by cartermp** [comment]
@aknot242 have you had a chance to take a look at the CLA?

**Comment by aknot242** [comment]
Hello, sorry for the delay. I have reviewed it, but I need to get additional approval before I sign it. It is in review by our Open Source submissions team to make sure I can contribute. I'm hoping to hear back this coming week.

**Comment by cartermp** [comment]
Sounds good!

**Comment by aknot242** [comment]
@cartermp - CLA signed. Thanks for your patience.

**Pull request merged**
