### PR TITLE
[zh] add contributing/style-guide.md

### PR DESCRIPTION
**Pull request by freezer712**
[zh] add contributing/style-guide.md

### CODE REVIEW

**Review by theletterf — COMMENTED** [review]
Interesting! I wonder if the style guide makes sense for a tech writer writing in Chinese.

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
> Interesting! I wonder if the style guide makes sense for a tech writer writing in Chinese.

I just checked and can confirm that that style guide makes sense for Chinese.

**Review by chalin — COMMENTED** [review]
This page will need to be updated to conform to https://opentelemetry.io/docs/contributing/localization/#translation-tips, in particular header IDs are missing.

**Review by theletterf — APPROVED** [review]

**Review by chalin — APPROVED** [review]
Ok, let's get this merged as is. I'll let @open-telemetry/docs-zh-approvers address the required updates (that I mentioned in my previous comment) to the page.

**Comment by chalin** [comment]
Ignoring Component-owners GH action failure for now and merging, since all other checks are green:

> image

**Pull request merged**
