### PR TITLE
update link to zone.js

### PR DESCRIPTION
**Pull request by signed**
The zone.js repo has been moved to angular mono repo

### CODE REVIEW

**Comment by cartermp** [comment]
@signed nice username. Could you _sign_ the CLA? Thanks!

**Comment by signed** [comment]
> Could you _sign_ the CLA? Thanks!

@cartermp Done

**Review by svrnm — APPROVED** [review]
lgtm

**Comment by svrnm** [comment]
thanks for your contribution @signed! 🎉 -- first PR merged in 1 hour, that's the fast lane to become an otel contributor :-)

**Pull request merged**
