### PR TITLE
Change "Language Feature Reference" table in demo docs

### PR DESCRIPTION
**Pull request by pellared**
Related to https://github.com/open-telemetry/opentelemetry-specification/issues/2866

Lots of the things documented under "Auto Instrumentation" are in fact about using "instrumentation libraries".

### CODE REVIEW

**Comment by cartermp** [comment]
I think this is incorrect since, at the very minimum, the Java service uses the autoinstrumentation agent.

**Comment by pellared** [comment]
> I think this is incorrect since, at the very minimum, the Java service uses the autoinstrumentation agent.

But e.g. Go, .NET are using manual instrumentation libraries. Therefore the existing header is misleading.

**Comment by pellared** [comment]
@cartermp I added a separate column. I am not sure if it won't be more readable to remove the whole "Language Feature Reference" section and add more info in "Service Documentation" section. E.g.

```
- [Ad Service](services/ad/) (Java, Automatic Instrumentation, Manual Instrumentation)
- [Cart Service](services/cart/) (.NET Instrumentation Libraries, Manual Instrumentation)
...
```

WDYT?

**Review by Kielek — APPROVED** [review]
Probably also https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/demo/trace-features.md should be adjusted

**Comment by pellared** [comment]
And https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/demo/metric-features.md as well

**Review by svrnm — APPROVED** [review]

**Review by svrnm — APPROVED** [review]

**Pull request merged**
