### PR TITLE
Update discussion-group.md

### PR DESCRIPTION
**Pull request by reese-lee**
This PR includes:

- New dates for the sessions through May
- Info about how to find summaries of past discussions on the OTel blog 
- Luma link for APAC sessions

---

**Preview**: https://deploy-preview-2501--opentelemetry.netlify.app/community/end-user/discussion-group/

### CODE REVIEW

**Review by musingvirtual — APPROVED** [review]
LGTM

**Review by cartermp — APPROVED** [review]
LGTM as well, if you run `npm run test` it should update the formatting refcache

**Comment by reese-lee** [comment]
Hm so I ran `npm run-script prettier:write` and it _looks_ like it did the thing?

Screen Shot 2023-03-13 at 6 01 11 PM

**Review by chalin — APPROVED** [review]
✨

**Pull request merged**
