### PR TITLE
Add operator runbooks

### PR DESCRIPTION
**Pull request by bogdan-at-adobe**
This replaces https://github.com/open-telemetry/opentelemetry-operator/pull/3240. 
The initial purpose was to fix the wrong runbook_url in the [PrometheusRule in the operator chart](https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1317/files#diff-30342bbb9d5db23b5ad8324ca5fa8462c4fe7a0cbb46d61de745ff3b32235205L35). This provides a correct url.

### CODE REVIEW

**Comment by theletterf** [comment]
We might want to add "runbooks" and "runbook" to the general cSpell exceptions.

**Review by jaronoff97 — APPROVED** [review]

**Review by theletterf — APPROVED** [review]

**Pull request merged**
