### PR TITLE
Update vendors.yaml - Centreon

### PR DESCRIPTION
**Pull request by fmattesct**
contact : fmattes@centreon.com
https://github.com/centreon/centreon

Centreon is offering native OTLP agents support, for metrics collection.

### CODE REVIEW

**Comment by theletterf** [comment]
@fmattesct Could you sign the CLA? Thanks!

**Comment by fmattesct** [comment]
> @fmattesct Could you sign the CLA? Thanks!

Hi,
Iam not authorized to do this. I sent the request to my legal department.

**Comment by svrnm** [comment]
@fmattesct any updates?

**Comment by fmattesct** [comment]
> @fmattesct any updates?

Hi, should be OK now.

**Review by cartermp — APPROVED** [review]

**Review by cartermp — APPROVED** [review]

**Pull request merged**
