### PR TITLE
Fix parameter warning for set_status

### PR DESCRIPTION
**Pull request by yenchenLiu**

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks, changes look good (ran locally in a sample app)

**Review by srikanthccv — COMMENTED** [review]
This is not really needed going forward and I think you are seeing this warning because the change exists in the RC release but your installed package is stable and <= 1.11.

**Comment by chalin** [comment]
> This is not really needed going forward and I think ...

@srikanthccv - so, we should just close this PR (since the problem is transient)?

**Comment by srikanthccv** [comment]
I don't mind merging this because it is still valid.

**Review by srikanthccv — APPROVED** [review]

**Review by chalin — APPROVED** [review]
Thanks all!

**Pull request merged**
