### PR TITLE
Refresh go docs

### PR DESCRIPTION
**Pull request by cartermp**
Pulling in the improvements made upstream

Preview: https://deploy-preview-1003--opentelemetry.netlify.app/

### CODE REVIEW

**Comment by cartermp** [comment]
Argh, more upstream link changes need to be made, yay for my changes 🙃 

I guess this can also go under the "docs coming from upstream sources can make things harder"

**Comment by chalin** [comment]
> Argh, more upstream link changes need to be made, yay for my changes 🙃
> 
> I guess this can also go under "docs coming from upstream sources can make things harder"

Yes, this is valuable feedback, ... which you might want to reiterate in #989?

**Comment by cartermp** [comment]
@chalin this is ready now.

**Review by chalin — APPROVED** [review]

**Comment by chalin** [comment]
Thanks!

**Pull request merged**
