### PR TITLE
added-go-instrument

### PR DESCRIPTION
**Pull request by nikolaydubina**
second attempt. previous attempt was corrupting some submodules due to running `npm run fix`, and I do not know how to fix that.

previous PR: https://github.com/open-telemetry/opentelemetry.io/pull/3993

### CODE REVIEW

**Comment by nikolaydubina** [comment]
cc: @cartermp

**Comment by nikolaydubina** [comment]
I see linter for spellcheck fails for unknown word. but this is my name!
image

**Comment by nikolaydubina** [comment]
other linter recommends to run npm fix, but this what broke submodules last time... 
image

**Comment by nikolaydubina** [comment]
ok, I leave this PR in your hands now. if you want to fix and merge it.

**Comment by svrnm** [comment]
> ok, I leave this PR in your hands now. if you want to fix and merge it.

We can not fix and merge it if you delete the PR, also if a word is unknown to the spell checker you can fix it by adding it to the ignore list at the top of the file, see other registry entries for example, but basically:

```
#cSpell:ignore <words>
```

**Pull request closed without merging**
