### PR TITLE
collapse block fix

### PR DESCRIPTION
**Pull request by kemsguy7**
This pr resolves issue: #5405  where I  resolved an issue in the nodeJs documentation Page; improving the visibility of long invisible code blocks wrapped around previous with HTML `summary` tag . 

### **Key changes** 

- Created a new shortcode **preview-fade.html** in the **themes/docsy/layouts/shortcodes** directory to hold the expandable *Show More* that shows the first 3 lines of the codeblock
- Added in styling for the new Layout by creating a new scss file in **themes/docsy/assets/scss/shortcodes/preview-fade.scss**
- Edited the Markdown file to include my newly custom-created shortcode
- Added a Javascript file for the *Show More* to toggle the collapsible section based on its state in **themes/docsy/assets/js/preview-fade.js**

### **Demo**
Screenshot 2024-10-23 at 03 33 56

### Preview

- https://deploy-preview-5463--opentelemetry.netlify.app/docs/languages/js/getting-started/nodejs/#run-the-instrumented-app

### CODE REVIEW

**Comment by kemsguy7** [comment]
@svrnm , please kindly review. 

Also I have an issue with linking the Javascript. Please where do you think I should link it, should that be in the root asset folder or in the theme(docsy) asset folder?

**Comment by svrnm** [comment]
> @svrnm , please kindly review.
> 
> Also I have an issue with linking the Javascript. Please where do you think I should link it, should that be in the root asset folder or in the theme(docsy) asset folder?

In the root asset folder. the theme is a git submodule and shouldn't be touched. If we like the solution we can talk about upstreaming it to docsy (cc @chalin)

Can you add the javascript and the shortcode file you used? right now the PR is broken and I can not preview it.

**Comment by kemsguy7** [comment]
@svrnm  here's an update on this pr
I moved all files to the root directory,
 -**The shortcode** can be found in **layouts/shortcodes/preview-fade.html**
-The scss file can be found in **assets/scss/_preview-fade.scss**, I also imported the preview scss into the **_styles_project.scss** file
-The javascript can be found in **assets/js/preview-fade.js**, 
-I also updated the **layouts/partials/hooks/body-end.html** with the js import
`{{ partial "script.html" (dict "src" "js/preview-fade.js") -}}`

The shortcode and assets are not being applied after moving them to the root directory

**Comment by svrnm** [comment]
@kemsguy7 thanks!

Please take a look at the preview, it seems there is something not working as expected:

https://deploy-preview-5463--opentelemetry.netlify.app/docs/languages/js/getting-started/nodejs/

**Review by svrnm — CHANGES_REQUESTED** [review]

**Review by chalin — CHANGES_REQUESTED** [review]
Thanks for this proposal @kemsguy7.

@svrnm - at first glance, my preference would be for something much simpler. Can we discuss this (possibly at the next OTel comms meeting) before moving forward with a solution?

**Pull request closed without merging**
