### PR TITLE
Python cookbook http headers

### PR DESCRIPTION
**Pull request by svrnm**
Super helpful feature, that is right now only [documented for java](http://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#capturing-http-request-and-response-headers) but also available for python, so I added some words on it to the cookbook :-)

Preview: https://deploy-preview-1717--opentelemetry.netlify.app/docs/instrumentation/python/cookbook/#capture-http-request-and-response-headers

cc: @sanketmehta28

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by svrnm** [comment]
@open-telemetry/python-approvers: can we add this item to the cookbook?

**Comment by srikanthccv** [comment]
@svrnm I think it makes more sense to add this under the automatic instrumentation https://deploy-preview-1717--opentelemetry.netlify.app/docs/instrumentation/python/automatic/. Maybe introduce a `configuration` section similar to java?

**Comment by svrnm** [comment]
> @svrnm I think it makes more sense to add this under the automatic instrumentation https://deploy-preview-1717--opentelemetry.netlify.app/docs/instrumentation/python/automatic/. Maybe introduce a `configuration` section similar to java?

Agreed, let me try to move that.

**Comment by svrnm** [comment]
@srikanthccv: https://deploy-preview-1717--opentelemetry.netlify.app/docs/instrumentation/python/automatic/#configure

**Review by srikanthccv — APPROVED** [review]

**Pull request merged**
