### PR TITLE
Instrumentation examples resources

### PR DESCRIPTION
**Pull request by mnadeem**
As per the recommendations on  https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2354  Submitting the Pull request 

CC: @austinlparker

### CODE REVIEW

**Comment by flands** [comment]
@mnadeem please sign the CLA

**Comment by mnadeem** [comment]
@flands  I have not done it before, How do I do it ? Appreciate your help

**Comment by mnadeem** [comment]
@flands  I have not done it before, How do I do it ? Appreciate your help

**Comment by flands** [comment]
@mnadeem select details next to easycla below and follow prompts

**Comment by mnadeem** [comment]
image

**Comment by flands** [comment]
hmm adblocker? can you try incognito? otherwise try: https://easycla.lfx.linuxfoundation.org/#/

**Comment by mnadeem** [comment]
Same issue in incognitive as well

image

**Comment by flands** [comment]
Hmm only other thing I can think of is to contact: https://support.linuxfoundation.org/

**Comment by mnadeem** [comment]
Lots of users are facing the same issue

https://support.docusign.com/s/question/0D51W00007uwh4q/getting-the-unable-to-start-the-signing-process

**Comment by mnadeem** [comment]
I have signed it, received an email as well

image

 Still showing `Missing CLA Authorization.`

**Comment by mnadeem** [comment]
Signed the document thrice, github still showing `Missing CLA Authorization.`

**Comment by SergeyKanzhelev** [comment]
> * ❌ The commit ([ff1b850](https://github.com/open-telemetry/opentelemetry.io/commit/ff1b850feb84cd6d6c0f4c5ed04d818be04ba625) ,7c5334b5abf40ce996c50ec8074e62eeb506ae64) is missing the User's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve.For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

@mnadeem this ^^^ is the reason. Make sure to associate your commits with the GitHub account. When looking at commits list for this PR, and hover over your name, it doesn't make it a link. This means that GitHub knows the name and e-mail from the commit message, but cannot map it to your GitHub user

**Comment by mnadeem** [comment]
I have changed my primary email address in github settings, and it showing the link correctly, 
I have signed the document again

image

**Comment by mnadeem** [comment]
Let me recreate another pull request

**Comment by mnadeem** [comment]
Created new one 

https://github.com/open-telemetry/opentelemetry.io/pull/455

**Pull request closed without merging**
