### PR TITLE
Fix contributor guide URL

### LINKED ISSUE #4971: [docs/contributing] OpenTelemetry Contributor Guide link is broken
In https://opentelemetry.io/docs/contributing/, the link here for the OpenTelemetry Contributor Guide is broken:
>For guidance on how to contribute to the OpenTelemetry project in general, see the [OpenTelemetry Contributor Guide](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md) , which provides details on the Contributor License Agreement and the Code of Conduct. Every language implementation, Collector, and conventions [repository](https://github.com/open-telemetry/) has its own specific contributing guides.

Fix that by using the link:  https://github.com/open-telemetry/community/blob/main/guides/contributor/README.md

### PR DESCRIPTION
**Pull request by Metal-Bat**
fixes #4971

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
Thanks for the fix @Metal-Bat.

LGTM, but ... I have a question for @open-telemetry/docs-maintainers: generally, an `en` page fix **must not** be propagated to non-`en` languages, since the locale maintainers need to update the `default_lang_commit` too. We might want to make an exception when a 404 is being fixed? WDYT?

I'm leaning towards this PR be exclusively for `en` pages. Other locales can handle their own page updates. But I'm willing to be convinced otherwise. I don't have a strong opinion about this.

/cc @emdneto

**Comment by Metal-Bat** [comment]
I think you are making a good point
so if teams accept this idea i would be glad to add persian documents to this project

Thank you everyone

**Comment by theletterf** [comment]
> I'm leaning towards this PR be exclusively for en pages. 

+1. Exceptions might become unmanageable in the long run.

**Comment by svrnm** [comment]
> > I'm leaning towards this PR be exclusively for en pages.
> 
> +1. Exceptions might become unmanageable in the long run.

Agred.

>  so if teams accept this idea i would be glad to add persian documents to this project

Thanks for the offer @Metal-Bat! Can you raise a dedicated issue for that? Note, that we need at least 2 people, 3 would be even better to work on that, since we as non-persian speakers can not help you with reviewing the content. Also note, that localizations are still a new thing to the OpenTelemetry website, so onboarding of new languages is still a slow process

**Comment by chalin** [comment]
@Metal-Bat - please drop the non-en page changes from this PR.

**Comment by Metal-Bat** [comment]
> > > I'm leaning towards this PR be exclusively for en pages.
> > 
> > 
> > +1. Exceptions might become unmanageable in the long run.
> 
> Agred.
> 
> > so if teams accept this idea i would be glad to add persian documents to this project
> 
> Thanks for the offer @Metal-Bat! Can you raise a dedicated issue for that? Note, that we need at least 2 people, 3 would be even better to work on that, since we as non-persian speakers can not help you with reviewing the content. Also note, that localizations are still a new thing to the OpenTelemetry website, so onboarding of new languages is still a slow process

sure i will open an issue and i will find some people to start this documentation

**Comment by Metal-Bat** [comment]
> @Metal-Bat - please drop the non-en page changes from this PR.

**Comment by Metal-Bat** [comment]
> > I'm leaning towards this PR be exclusively for en pages.

sure

**Review by emdneto — APPROVED** [review]

**Review by chalin — APPROVED** [review]
✨

**Comment by chalin** [comment]
Thanks all!

> sure i will open an issue and i will find some people to start this documentation

@Metal-Bat et al. - heads up that Docsy (and hence this repo) doesn't fully support RTL languages yet. I'm working on it, but the feature might not land for a few weeks or months -- though I do see it happening before the end of the year. Reference: https://github.com/google/docsy/issues/1442.

**Comment by Metal-Bat** [comment]
> Thanks all!
> 
> > sure i will open an issue and i will find some people to start this documentation
> 
> @Metal-Bat et al. - heads up that Docsy (and hence this repo) doesn't fully support RTL languages yet. I'm working on it, but the feature might not land for a few weeks or months -- though I do see it happening before the end of the year. Reference: [google/docsy#1442](https://github.com/google/docsy/issues/1442).

great thanks

**Pull request merged**
