### PR TITLE
Add JS API ref to sidebar

### PR DESCRIPTION
**Pull request by cartermp**
Contributes to https://github.com/open-telemetry/opentelemetry.io/issues/1808

### CODE REVIEW

**Comment by svrnm** [comment]
I think this should point to https://open-telemetry.github.io/opentelemetry-js-api/, because https://open-telemetry.github.io/opentelemetry-js is for the SDK

**Comment by svrnm** [comment]
> What we need is a single API-reference page that would allow users to visit either of the following links:
> 
> * https://open-telemetry.github.io/opentelemetry-js
> * https://open-telemetry.github.io/opentelemetry-js-api
> 
> That _could_ be setup over https://open-telemetry.github.io, but it might be easier (and more under our control), to keep the **API** page (which you removed in this PR), and from that page offer these two API-reference links. WDYT?

not ideal since it's different from the other languages then, but yes, let's do it that way.

**Comment by chalin** [comment]
> not ideal since it's different from the other languages

Agreed.

Then maybe we can try it the way @cartermp has it here ... because https://open-telemetry.github.io/opentelemetry-js/ does have a link to the "API" API-reference in the page header. Maybe that's enough for now? We give it a try and collect user feedback. WDYT?

**Comment by cartermp** [comment]
I'm down like a clown! And also happy to see if there's a way to improve the rendering of the API reference(s) in the page we link do over in the JS repo.

**Comment by chalin** [comment]
> I'm down like a clown! And also happy to see if there's a way to improve the rendering of the API reference(s) in the page we link do over in the JS repo.

Coolio. If you end up opening an issue over the JS repo for that, please link it here. Thanks!

**Review by chalin — APPROVED** [review]
✨

**Comment by cartermp** [comment]
Filed here, we'll see what can be done https://github.com/open-telemetry/opentelemetry-js/issues/3362

**Review by svrnm — APPROVED** [review]
👍

**Pull request merged**
