### PR TITLE
Remove requirements for flask and werkzeug in Pythn docs

### PR DESCRIPTION
**Pull request by cartermp**
Flask 3 is now supported in python instrumentations, meaning we can remove the specific instructions for installation + various warnings about that.

Ref: https://github.com/open-telemetry/opentelemetry.io/pull/4034#issuecomment-1962066146

cc @aabmass

### CODE REVIEW

**Review by svrnm — APPROVED** [review]

**Review by swiatekm-sumo — CHANGES_REQUESTED** [review]
The new instrumentation release isn't yet the default in the operator, so if we want to drop the notice in the operator docs, we should wait for its next release.

**Review by theletterf — APPROVED** [review]

**Comment by swiatekm-sumo** [comment]
I'm the release manager for operator 0.95.0, so I'll just approve this PR once it's out, if that's ok with everyone.

**Comment by cartermp** [comment]
@swiatekm-sumo when is the new operator release planned? If it's soon then we can just wait until that's done, but if not then I'll change the Operator docs

**Comment by swiatekm-sumo** [comment]
@cartermp should be out by the end of this week. If you'd prefer to drop the operator change from this PR, I can submit it by myself once the operator release is out.

**Comment by cartermp** [comment]
Sounds good @swiatekm-sumo. I've updated everything here, good to merge?

**Review by swiatekm-sumo — APPROVED** [review]

**Pull request merged**
