### PR TITLE
[python] Add doc for disabling instrumentation for python

### PR DESCRIPTION
**Pull request by TylerHelmuth**
Adds docs to Python's auto-instrumentation config and the k8s operator auto-instrumentaiton config for python explaining how to omit specific packages from instrumentation.  This is an important feature in auto-instrumentation as instrumenting everything can lead to too much data or noise.

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
Prettifying resulted in a lot of extraneous changes.  Opened https://github.com/open-telemetry/opentelemetry.io/pull/2197 to address them separately.

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
@open-telemetry/operator-approvers and @open-telemetry/python-approvers please take a look!

**Review by srikanthccv — APPROVED** [review]

**Comment by srikanthccv** [comment]
On a separate note, there are many other (undocumented) config options Python auto instrumentation supports. It will be good to document them under the Agent Config section.

**Comment by cartermp** [comment]
@srikanthccv yes, agreed! Is there a good list to look at somewhere, even if it's just in code somewhere? I'll want to at least get that documented.

**Comment by srikanthccv** [comment]
Something I could think of immediately
- https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib%20OTEL_PYTHON&type=code
- https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-python-contrib+OTEL_INSTRUMENTATION&type=code

>I'll want to at least get that put into an issue.

Please do. There are probably more options buried inside the code base. I will add more to issue as I dig more.

**Comment by cartermp** [comment]
Thanks, filed https://github.com/open-telemetry/opentelemetry.io/issues/2214

**Review by svrnm — APPROVED** [review]
lgtm

**Pull request merged**
