### PR TITLE
Fix indentations in blog: otel-in-focus

### PR DESCRIPTION
**Pull request by windsonsea**
Adjust the wrapping position and some indentations in:

```
content/en/blog/2023/otel-in-focus-01.md
```

### CODE REVIEW

**Review by chalin — CHANGES_REQUESTED** [review]
Hi. Did you achieve this using Prettier? I believe that the previous formatting is the result of having run Prettier, and so should be preserved (since we're aiming to run Prettier by default as a PR pre-check).

/cc @svrnm

**Comment by windsonsea** [comment]
Hi @chalin , yes, I understand the original text was organized by running `Prettier`.

I'm not sure whether we need to perform some minor adjustments after `Prettier`, such as:

- Put the link url and its [link text] on a same line
- Provide a consistent indentations for the bulleted list

**Comment by chalin** [comment]
> I'm not sure whether we need to perform some minor adjustments after `Prettier`,

Eventually the project will be settling on Prettier as the official formatter. So generally, we shouldn't be tweaking files after Prettier has formatted it.

> * Provide a consistent indentations for the bulleted list

Oh! I hadn't seen that the list item indentions were off. Yes, that should be fixed. I think that in this case Prettier respects the indentation that the file was originally written in.

If you re-run Prettier over the changes that you have made, does Prettier un-indent the lists?

**Comment by windsonsea** [comment]
Hi @chalin , well noted. I performed two actions just now:

1. Restore this page to original
2. Run `npx prettier --w content/en/blog/2023/otel-in-focus-01.md`
3. git commit and push again. 

You are correct. The default `prettier` looks good enough.

**Review by chalin — APPROVED** [review]
Wonderful! 🎉

**Pull request merged**
