### PR TITLE
[ja] Temporarily patch page to avoid link-check failure

### PR DESCRIPTION
**Pull request by katzchang**
Fix for #5423

### CODE REVIEW

**Comment by katzchang** [comment]
```
$ npm run fix:htmltest-config

> fix:htmltest-config
> scripts/htmltest-config.sh

Warning: Unrecognized htmltest IgnoreDirs config from front matter in file 'content/pt/docs/_index.md': IgnoreDirs: {}
```
When I try to `run fix:htmltest-config`, I get this error. After deleting the `IgnoreDirs: {}` statement in `content/pt/docs/_index.md`, the problem goes away. 

@chalin Do you think okay to delete it?

**Comment by chalin** [comment]
That should have been caught earlier. I need to fix the CI scripts first. Let me do that before approving this PR.

**Comment by chalin** [comment]
Waiting for the following to get merged, then we'll rebase this PR:

- #5612

**Review by chalin — APPROVED** [review]

**Pull request merged**
