### PR TITLE
[Blog] Learn how to instrument nginx with OpenTelemetry

### PR DESCRIPTION
**Pull request by svrnm**
@DebajitDas & @kpratyus have released a first version of the nginx module, in this blog post I give a hands on introduction on how to use it.  

Preview: https://deploy-preview-1624--opentelemetry.netlify.app/blog/2022/instrument-nginx/

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
I have some copyedits, but they are sprinkled out, so I'm just going to commit the delta (https://github.com/open-telemetry/opentelemetry.io/pull/1624/commits/9e24102f87201ef7b094f407543f7d3a09d77177, see below). Please review the commit and feel free to comment / adjust as necessary. Hopefully, this is ok with you.

**Comment by chalin** [comment]
Since the images will very likely only be used in this post, I've repackaged the files as a Hugo page bundle (via https://github.com/open-telemetry/opentelemetry.io/pull/1624/commits/9f08fd3e12f727647311021ab376f85cdf1e0cbb). PTAL

**Comment by svrnm** [comment]
@chalin thanks for copy edits, packacking & committing them directly :-) all the changes are looking good to me.

**Review by chalin — APPROVED** [review]
I'm glad that you're ok with the changes. Then this LGTM! :)

**Review by chalin — APPROVED** [review]

**Comment by 880831ian** [comment]
Hi author, I followed this blog step by step, and encountered the following problem in the final frontend Node.js. When the frontend finished running docker, the following error would be displayed:

```
test-frontend-1   | /app/app.js:14
test-frontend-1   | sdk.start().then(() => {
test-frontend-1   |            ^
test-frontend-1   |
test-frontend-1   | TypeError: Cannot read properties of undefined (reading 'then')
test-frontend-1   |     at Object.<anonymous> (/app/app.js:14:12)
test-frontend-1   |     at Module._compile (node:internal/modules/cjs/loader:1198:14)
test-frontend-1   |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
test-frontend-1   |     at Module.load (node:internal/modules/cjs/loader:1076:32)
test-frontend-1   |     at Function.Module._load (node:internal/modules/cjs/loader:911:12)
test-frontend-1   |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
test-frontend-1   |     at node:internal/main/run_main_module:22:47
```

<br>

I tried adapting the Node.js program to:

```
const opentelemetry = require('@opentelemetry/sdk-node');
const {
  getNodeAutoInstrumentations,
} = require('@opentelemetry/auto-instrumentations-node');
const {
  OTLPTraceExporter,
} = require('@opentelemetry/exporter-trace-otlp-http');
const express = require('express');
const http = require('http');

const sdk = new opentelemetry.NodeSDK({
  traceExporter: new OTLPTraceExporter(),
  instrumentations: [getNodeAutoInstrumentations()],
});

(async () => {
  await sdk.start();

  const app = express();

  app.get('/', (_, response) => {
    const options = {
      hostname: 'nginx',
      port: 80,
      path: '/',
      method: 'GET',
    };
    const req = http.request(options, (res) => {
      console.log(`statusCode: ${res.statusCode}`);
      res.on('data', (d) => {
        response.send('Hello World');
      });
    });
    req.end();
  });

  app.listen(8000, () => {
    console.log('Listening for requests on port 8000');
  });
})();
```

<br>

It works fine, but in jaeger what is shown is not accessing the frontend

截圖 2023-07-21 下午4 12 48

<br>

Is there any good suggestion to adjust the direction? Thank ~~~

**Comment by svrnm** [comment]
@880831ian can you raise an independent issue for your question, as this PR is closed

**Comment by 880831ian** [comment]
@svrnm  ok, I open a new issue, thank

**Comment by 880831ian** [comment]
I have opened a new issue, please help
https://github.com/open-telemetry/opentelemetry.io/issues/3059

**Pull request merged**
