### PR TITLE
Add basic getting started for swift

### PR DESCRIPTION
**Pull request by svrnm**
contributes to #2623

I have not a lot of experience with Swift, so I hope what I wrote makes sense to a proper swift developer. The purpose of this is not to be all neat & tidy, but quick and easy to follow, such that people can continue their journey from there.

### CODE REVIEW

**Review by vvydier — APPROVED** [review]
I tried the instructions and was able to get the Webserver and the otel StdoutExporter set up in a few minutes. Its a good addition to the docs

**Comment by svrnm** [comment]
> I tried the instructions and was able to get the Webserver and the otel StdoutExporter set up in a few minutes. Its a good addition to the docs

Thank you for taking a look @vvydier

**Review by cartermp — APPROVED** [review]
So I think this is good, but my understanding is that Swift is primarily used for iOS apps instead of server apps. I don't want to block on this because of that, but I think we'd be remiss not to have an iOS getting started scenario.

But that's a whole new kind of getting started app.

**Comment by svrnm** [comment]
> So I think this is good, but my understanding is that Swift is primarily used for iOS apps instead of server apps. I don't want to block on this because of that, but I think we'd be remiss not to have an iOS getting started scenario.
> 
> But that's a whole new kind of getting started app.

Based on what I see with Vapor and some other frameworks, server side swift is a thing on it's own. I think what we eventually should have is 2 Getting Started docs like we have it in JavaScript (Node.JS & Browser, here: Server & Client ?)

**Pull request merged**
