### PR TITLE
PR-actions workflow with support for `/fix:format`

### PR DESCRIPTION
**Pull request by chalin**
- A first attempt at a comment-triggerable bot action to reformat files in a PR.
- Contributes to #2448

### CODE REVIEW

**Comment by chalin** [comment]
Dunno if it'll trigger on this PR. Here goes ... 
/fix:format

**Comment by chalin** [comment]
Hey @trask: what's the best way to test & debug new GH actions (that trigger on comments) like the one in this PR?

**Comment by trask** [comment]
push the PR to the `main` branch on your fork, then open a PR on your fork (targeting `main` on your fork as opposed to targeting the otel repo), then comment on that PR

btw, we have similar here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/.github/workflows/comment-driven-automation.yml

the problem which I don't have solution for yet is that when it pushes the commit back to the PR, it doesn't trigger workflow, and the only way to trigger workflow is to manually close and re-open the PR, e.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7881#issuecomment-1440887920

**Comment by chalin** [comment]
Oh, very cool that y'all have a script like that already. Thanks for guidance @trask, and the heads up regarding the (non-)triggering issue.

**Comment by chalin** [comment]
@cartermp @svrnm (cc @trask): this is ready for review. It's a first cut, but it's functional. 

I tested it from another repo. As mentioned in [Commits made by this Action do not trigger new Workflow runs](https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs):

> The resulting commit will not trigger another GitHub Actions Workflow run.

But we can always manually re-trigger the "Check format" action. Maybe we'll find a better solution down the line.

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
Let's go with this for now and we can adjust if needed!

**Comment by chalin** [comment]
@cartermp - FYI, I've tested the workflow and it goes through all the paces but the pushed commit doesn't make it back into the PR 🤷🏼‍♂️. I'll investigate as soon as I can, but it might not be until late next week.

**Comment by chalin** [comment]
@cartermp - hey, it did work! Just took longer than I expected 🤷🏼‍♂️.

**Pull request merged**
