### PR TITLE
Auto-update registry versions (a0e217e429e93dbcd71fe91fc6379dd5b10a834e)

### PR DESCRIPTION
**Pull request by opentelemetrybot**
- (npm): Updated version from 3.11.0 to 3.12.0 in ./data/registry/exporter-js-instana.yml
- (npm): Updated version from 1.25.0 to 1.25.1 in ./data/registry/exporter-js-jaeger.yml
- (npm): Updated version from 0.52.0 to 0.52.1 in ./data/registry/exporter-js-prometheus.yml
- (npm): Updated version from 1.25.0 to 1.25.1 in ./data/registry/exporter-js-zipkin.yml
- (npm): Updated version from 0.52.0 to 0.52.1 in ./data/registry/instrumentation-js-fetch.yml
- (npm): Updated version from 0.52.0 to 0.52.1 in ./data/registry/instrumentation-js-grpc.yml
- (npm): Updated version from 0.52.0 to 0.52.1 in ./data/registry/instrumentation-js-http.yml
- (npm): Updated version from 0.52.0 to 0.52.1 in ./data/registry/instrumentation-js-xml-http-request.yml
- (gems): Updated version from 0.5.1 to 0.5.3 in ./data/registry/instrumentation-ruby-active-support.yml
- (gems): Updated version from 0.24.4 to 0.24.5 in ./data/registry/instrumentation-ruby-faraday.yml
- (gems): Updated version from 0.0.2 to 0.0.3 in ./data/registry/tools-ruby-rspec-matcher.yml

### CODE REVIEW

**Review by svrnm — APPROVED** [review]

**Review by xrmx — APPROVED** [review]

**Comment by cartermp** [comment]
whoops @svrnm looks like the fixaller went and spell-corrected everything

**Comment by svrnm** [comment]
> whoops @svrnm looks like the fixaller went and spell-corrected everything

Probably because this was not in sync with https://github.com/open-telemetry/opentelemetry.io/pull/4728

**Comment by svrnm** [comment]
I _think_ we should be able to close this one safely since the updates should be picked up by later runs

**Pull request closed without merging**
