### PR TITLE
Improve JS Instrumentation Docs

### PR DESCRIPTION
**Pull request by legalimpurity**
Since https://github.com/open-telemetry/opentelemetry-js/pull/4427 the method addMetricReader on MeterProvider is deprecated and will be removed in SDK 2.0. Would be better if we remove deprecated methods from documentation and change the sample code to reflect the new way to add metric reader.

### CODE REVIEW

**Review by theletterf — APPROVED** [review]
@open-telemetry/javascript-maintainers Please have a look!

**Comment by cartermp** [comment]
It seems like this change is released, which would make it good, but I'd like @open-telemetry/javascript-approvers to confirm

**Review by pichlermarc — APPROVED** [review]
Yep, that's the new way of adding `MetricReader`s 
Thanks for taking care of this. :+1:

**Review by svrnm — APPROVED** [review]

**Comment by svrnm** [comment]
thank you @legalimpurity !

**Pull request merged**
