### PR TITLE
Update instrumentation.md

### PR DESCRIPTION
**Pull request by rahuldimri**
End span outside task process doesn't work #934

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Looks good docs-wise, will tag erlang/elixir approvers

**Comment by cartermp** [comment]
@open-telemetry/erlang-approvers could you all take a look? Also, we should probably add y'all as approvers to this subsection of the docs

**Review by ferd — APPROVED** [review]
Yep, that sounds like a correct edit. There's a bit of a semantic difference at the core of the Erlang and Elixir snippets: the task in Elixir is synchronous (due to the `Task.await/1` call) and the one in Erlang is asynchronous, so the old and new Elixir ordering of operations are equivalent.

That being said, things look more uniform this way and both example also look more similar, so this is a useful fix.

**Review by chalin — APPROVED** [review]
Thanks all!

**Comment by chalin** [comment]
@cartermp et all: does this close #934? If so, can you close it? Thanks!

**Comment by tsloughter** [comment]
Ah yup, thanks! :+1:

**Pull request merged**
