### PR TITLE
Update glossary.md to remove instrumentation lib where incorret

### PR DESCRIPTION
**Pull request by cijothomas**

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
There's a warning being emitted by the markdown checker:

> [Unused link or image reference definition: "spec-exporter-lib"] [Context: "[spec-exporter-lib]: /docs/spe..."]

That is, delete the (now) unused link definition `[spec-exporter-lib]`.

LGTM otherwise, but I'll let another approver give a thumbs up too.

**Review by cartermp — APPROVED** [review]
LGTM as well, modulo change to make the markdown linter happy.

**Comment by chalin** [comment]
I've removed it. The checker should be happy now. Thanks for the PR @cijothomas!

**Comment by chalin** [comment]
All green, merging 🚀

**Pull request merged**
