### PR TITLE
Added Python open telemetry project setup.

### PR DESCRIPTION
**Pull request by baravkareknath**
Added Python open telemetry project setup on windows platform using WSL.

### CODE REVIEW

**Comment by baravkareknath** [comment]
Submitting these documents for review. Please looks into python open telemetry project setup documentation on windows platform using WSL tool.

**Comment by svrnm** [comment]
@baravkareknath , thank you for your contribution, please sign the CLA, after that we can look into your commits and provide feedback

**Comment by baravkareknath** [comment]
Sign of CLA done please review

**Comment by svrnm** [comment]
@baravkareknath thank you for taking the time and effort to write about installing OpenTelemetry Python on WSL. Unfortunately this does not fit the OpenTelemetry documentation, as it reads like a blog post and not a piece of documentation that fits into the rest of the documentation. I suggest that the way it is right now, you publish it on your private blog and make it accessible to interested readers that way. We can not accept this contribution as-is.

If any of the steps to install WSL and then OpenTelemetry Python are special, in the sense that a "normal" WSL installation would fail people to run OpenTelemetry Python on their machine, please highlight those sections and we can discuss how we can incorporate them into the existing documentation.

**Comment by cartermp** [comment]
Thanks for the contribution, but I agree with @svrnm that we cannot take this as-is. Additionally, there doesn't appear to be anything in here wherein you need to follow specific instructions to get OTel up and running on WSL. These steps are more about how to set up WSL on a machine, not specific instructions for Python OTel + WSL. Given that, I think these changes are out of scope of the docs.

That said, this would make a great blog post if hosted elsewhere. I'd encourage you to do that, since there are no doubt people who struggle to set up WSL.

**Comment by baravkareknath** [comment]
Hi cartermp, is there any documentation to setup project using WSL on windows platform?

**Pull request closed without merging**
