### PR TITLE
Update to new java docs repo

### PR DESCRIPTION
**Pull request by trask**
I'm not sure if you prefer renaming the directory to match also `content-modules/opentelemetry-java` --> `content-modules/opentelemetry-java-docs?`

### CODE REVIEW

**Comment by trask** [comment]
the build doesn't like it, probably due to changing the submodule? the build log is not very descriptive, any ideas? thx

```
1:25:17 PM: Error fetching branch: https://github.com/open-telemetry/opentelemetry.dev pull/978/head
```

**Comment by trask** [comment]
@open-telemetry/docs-approvers wondering if this is the issue: https://answers.netlify.com/t/error-fetching-branch-after-trying-to-update-submodule/5370. can you try clearing the netlify cache?

**Review by chalin — COMMENTED** [review]
I'd like to instead propose that we move the content of the Java `website_docs` into **this** repo, rather than moving them out to yet another Java OTel repo. (That way your new repo can be for OTel Java examples.)

Thoughts @trask @austinlparker @tedsuo?

**Comment by chalin** [comment]
[To follow through with my comments from earlier] Months ago, language SIGs were offered the following two choices:

(1) Their docs would reside here in the docs/website repo (this is simplest and preferred choice), or 
(2) As a _convenience_ to language SIG contributors, the docs would be in the main code repo with a submodule used to bring in the docs into the website.

@austinlparker et al., I don't think that we want to offer yet a third option, esp. since the convenience of having the docs + code in the same repo is lost once the docs are being moved elsewhere, so (again), I'd strongly vote for the docs to be moved here.

**Comment by trask** [comment]
@austinlparker proposed similar: https://github.com/open-telemetry/opentelemetry-java/pull/3974#issuecomment-989411778

I believe the main concern to this is summarized by @jkwatson's comment:

> We also want to include non-website docs, with runnable code samples and gradle build scripts for them. I don't think that belongs in the website repo, does it?

**Comment by chalin** [comment]
Thanks for offering some context @trask. I'll see if @austinlparker and I can meet tomorrow to discuss this.

**Comment by austinlparker** [comment]
Sorry, this thread slipped my attention.

I agree that having code samples in this repository doesn't make a ton of sense, but my understanding that the rationale from maintainers to keep docs + samples in the main repo was to ensure they were updated alongside the SDK releases. If that isn't a concern any more, and they're going to be divorced from it anyway, then I'd strongly urge for _all_ documentation to be migrated directly into this repository, with a separate code sample repository being maintained. 

Our eventual goal would be to migrate all docs to the website at the end of the day (aside from things that don't make sense, like auto-generated API docs or things that require language-specific tooling; javadoc, et. al.) so that we can enable versioning of the documentation and promote the website as a "one stop shop" for OTel docs.

**Comment by austinlparker** [comment]
I'd really like to understand what Java (and other) SIGs need to feel comfortable with moving their docs here. Is it approve/merge permissions? We can do that with codeowners and whatnot.

**Comment by trask** [comment]
you will need to discuss this with @jkwatson and @anuraaga

I'm going to close this PR for now until it's resolved

**Comment by chalin** [comment]
> you will need to discuss this with @jkwatson and @anuraaga

FYI, I've created #989 so that we can hold our discussion there.

**Comment by cartermp** [comment]
In the interim @chalin @austinlparker can we go through with this PR? It solves a _now_ problem - getting existing enhancements to docs (e.g., how to configure automatic instrumentation) to be live on the site - which is important too.

How it gets organized is clearly important, but now that it's deferred to an issue for discussion I'd like to have the _now_ problem resolved 🙂

**Comment by chalin** [comment]
Thanks for the ping. Let me chat with @austinlparker about this later today, once I'm back at the office.

**Comment by austinlparker** [comment]
I suppose, yeah, if we're getting blocked on updates.

**Comment by cartermp** [comment]
Not sure why, but same build error - something funky needed to "refresh" the submodule or something?

**Comment by chalin** [comment]
> I suppose, yeah, if we're getting blocked on updates.

Ok, will proceed for now.

> Not sure why, but same build error - something funky needed to "refresh" the submodule or something?

It's actually a bit tricky to update -- which is another reason to avoid submodules when we can. I have another PR ready that changes the Java submodule, but I can't submit and merge until the broken links are fixed: https://github.com/open-telemetry/opentelemetry-java-docs/pull/7

**Comment by chalin** [comment]
Closing, as this PR won't work. I'll submit another soon.

**Comment by chalin** [comment]
Superseded by #995

**Pull request closed without merging**
