### PR TITLE
Publish OpenTracing-migration page

### LINKED ISSUE #1037: Add OT to OTel migration page
Add OpenTracing migration page:

- [x] #1083 
- [x] #1089
- [x] #1090
- [x] #1227

Depends on:

- #1036

(Per 22/01/13 Comms meeting discussions.)

### PR DESCRIPTION
**Pull request by chalin**
- Closes #1037

Preview: https://deploy-preview-1228--opentelemetry.netlify.app/docs/migration/opentracing

/cc @tedsuo @yurishkuro @calebmchenry @austinlparker

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]

**Comment by austinlparker** [comment]
I believe EasyCLA is borked due to this current incident -- https://www.githubstatus.com/incidents/tyc8wpsgr2r8

**Comment by yurishkuro** [comment]
I haven't been following PRs in this repo, but I am surprised why it does not get CI checks from Netlify posted. For instance, in the Jaeger docs we get tons of feedback from Netlify. Is there some integration missing?

image

**Comment by chalin** [comment]
> ... For instance, in the Jaeger docs we get tons of feedback from Netlify. Is there some integration missing?

@yurishkuro - We have similar checks here too:

> image

**Pull request merged**
