### PR TITLE
Updated dead links in glossary

### PR DESCRIPTION
**Pull request by harshita19244**

### CODE REVIEW

**Comment by harshita19244** [comment]
https://github.com/open-telemetry/opentelemetry.io/issues/497
Kindly review, tried resolving the above issue

**Review by flands — APPROVED** [review]

**Comment by sirandysaunders** [comment]
Thank you. I have no idea what I'm doing trying to launch a research business. Can you help me?

**Comment by sirandysaunders** [comment]
> https://github.com/open-telemetry/opentelemetry.io/issues/497
> 
> Kindly review, tried resolving the above issue

Help me please

**Review by sirandysaunders — COMMENTED** [review]
Perfect!

**Review by nievesmiguel — APPROVED** [review]

**Pull request merged**
