### PR TITLE
Add Honeycomb.io Go and Node Distros to Registry

### PR DESCRIPTION
**Pull request by vreynolds**
Add Honeycomb.io OpenTelemetry Go and Node.js Distros to Registry

### CODE REVIEW

**Comment by cartermp** [comment]
@chalin heh, fun timing with https://github.com/open-telemetry/opentelemetry.io/pull/2249 -- should 2249 happen first?

**Comment by chalin** [comment]
@cartermp - Yes, let's get #2249 in first. Thanks!

**Comment by chalin** [comment]
PR #2249 has been merged, and the "how to submit a post" instructions have been updated too (#2250).

I'm glad to resubmit this PR's addition if you'd like. Let me know.

**Comment by vreynolds** [comment]
reopened as #2254

**Pull request closed without merging**
