### PR TITLE
Added Strimzi project to the OpenTelemetry integrations page

### PR DESCRIPTION
**Pull request by ppatierno**
This PR adds the CNCF Strimzi project to the integrations list.

### CODE REVIEW

**Comment by ppatierno** [comment]
@svrnm maybe you can take a look at this? Not sure why there are some checks failing.

**Comment by chalin** [comment]
> @svrnm maybe you can take a look at this? Not sure why there are some checks failing.

Hi. I've made the necessary updated for you, see the last commit.

**Comment by chalin** [comment]
Preview of blog: https://deploy-preview-3454--opentelemetry.netlify.app/blog/2022/instrument-kafka-clients/

**Review by chalin — APPROVED** [review]
The build is green now.
@cartermp, thoughts?

**Review by cartermp — APPROVED** [review]

**Pull request merged**
