### PR TITLE
Add demo doc pages, drop tmp git submodule

### PR DESCRIPTION
**Pull request by chalin**
- Contributes to #2269
- Adds the demo doc pages "as is" (as they were created from the adjust script). I'll do clean up in subsequent PRs
- Drops the demo git submodule
- Reverts changes to the submodule-docs adjust and copy scripts

Preview: https://deploy-preview-2270--opentelemetry.netlify.app/docs/demo/

Note: I'll update the `CODEOWNERS` file in a followup PR.

/cc @open-telemetry/demo-approvers 

---

Note: Other than page meta data (date modified, etc), and GH commit references, there are no changes to the generated site files. And only the demo doc pages (and the sitemap) are affected by this PR:

```console
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff | wc -l
      38
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff | head 
diff --git a/docs/demo/current_architecture/index.html b/docs/demo/current_architecture/index.html
diff --git a/docs/demo/demo_features/index.html b/docs/demo/demo_features/index.html
diff --git a/docs/demo/demo_screenshots/index.html b/docs/demo/demo_screenshots/index.html
...
$ (cd public && git diff -bw --ignore-blank-lines) | grep ^diff | grep -v /docs/demo/
diff --git a/sitemap.xml b/sitemap.xml
$ (cd public && git diff -bw --ignore-blank-lines -I 'dateModified|lastmod|modified_time|text-muted|Last modified|/div|og:site_name|^\s+$') | head
$
```

### CODE REVIEW

**Review by mviitane — COMMENTED** [review]
I'm missing the original folder structure in the navigation. Now, only one of the folders are visible in the preview. However, it's fine if the improved navigation is added in the following PRs.

**Comment by julianocosta89** [comment]
The file `content/en/docs/demo/img/opentelemetry-logo-nav.png` is not being used anymore.
We should be good to remove it.

**Review by svrnm — APPROVED** [review]

**Comment by chalin** [comment]
@mviitane @julianocosta89: yes, I'll address those issues in followup PRs. Can one of you (or another demo-approver) approve this PR?

**Review by julianocosta89 — APPROVED** [review]

**Comment by chalin** [comment]
> I'm missing the original folder structure in the navigation. Now, only one of the folders are visible in the preview. However, it's fine if the improved navigation is added in the following PRs.

Here's the followup issue:

- #2274

**Comment by chalin** [comment]
And here's the followup PR:

- https://github.com/open-telemetry/opentelemetry.io/pull/2275

**Pull request merged**
