### PR TITLE
Add entry for baronfel/otel-startup-hook

### PR DESCRIPTION
**Pull request by baronfel**
I've created a standalone .NET CLR Startup Hook that uses the OLTP exporter to push spans to an OLTP Collector (via the OTel SDKs of course). This is useful for applications that are instrumented with System.Diagnostics.Activity, but for whatever reason can't take direct dependencies on the OTel SDK.

### CODE REVIEW

**Review by cartermp — APPROVED** [review]

**Comment by cartermp** [comment]
@baronfel if you run `/fix:format` it should work for you

**Comment by baronfel** [comment]
lol, I had just gotten my local environment npm installed on WSL to run that command :)

**Comment by cartermp** [comment]
okay, one more:

`/fix:refcache`

It's a pain, I know

**Comment by cartermp** [comment]
We really should just have a `fix:all` -- @svrnm @chalin @theletterf what do you think?

**Pull request merged**
