### PR TITLE
Fix bad filename in collector config doc

### PR DESCRIPTION
**Pull request by Aneurysm9**

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
Thanks, good catch

**Comment by cartermp** [comment]
Ugh, computes were a mistake. Netlify issues perhaps? @chalin any ideas?

**Comment by chalin** [comment]
Build failed on attempting to fetch the link checker. Might have been a transient failure. I relaunched the build.

**Comment by chalin** [comment]
Still failing on download. The Hugo build passes though.

**Review by chalin — APPROVED** [review]
Build is green now.

**Comment by cartermp** [comment]
For some reason the build isn't green still, and https://github.com/open-telemetry/opentelemetry.io/pull/2224 does the same thing, so I'll take one. Sorry @Aneurysm9, apparently Netlify really doesn't like this PR.

**Pull request closed without merging**
