### PR TITLE
Announce metrics RCs on production server

### PR DESCRIPTION
**Pull request by chalin**
Will merge at 9am PT today (05/18/22), unless someone says otherwise. /cc @mtwo @alolita @austinlparker

### CODE REVIEW

**Review by austinlparker — APPROVED** [review]
sgtm

**Comment by mtwo** [comment]
Sounds good! You may want to publish it one or two minutes early so that the cross-posts work when they go live!

On May 18, 2022, at 4:10 PM, Patrice Chalin ***@***.******@***.***>> wrote:


Will merge at 9am PT today (05/18/22), unless someone says otherwise. /cc @mtwo<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmtwo&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hr5bOzfeI40jB71CD5q8COSNX%2F%2B9AbqO1stuqEIF5aw%3D&reserved=0> @alolita<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falolita&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=apxrFO436kJ5o%2BChbHhrgqRxJ4XEspcIA%2B0HWtp5ZJo%3D&reserved=0> @austinlparker<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faustinlparker&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ADbziHhr8THb1joMTpUvrI8%2BiLnGuFjtOqdT0pHEBZg%3D&reserved=0>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/open-telemetry/opentelemetry.io/pull/1361<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry.io%2Fpull%2F1361&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jZ7yeDQg5Y6viT8T8HPOIF9pqYt9%2FwsxMCLLLWCw1w0%3D&reserved=0>

Commit Summary

  *   92b7b1e<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry.io%2Fpull%2F1361%2Fcommits%2F92b7b1e1ed2e5fcb1cef8567f8f887ffbb53625f&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o5Farqif1tNDcYbGuEwWsvVsXS5iq7%2FE5SgTWBvK7ck%3D&reserved=0> Announce metrics RCS

File Changes

(1 file<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry.io%2Fpull%2F1361%2Ffiles&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iBHAbuRvrDthKFdwVH4vU7%2FafLvEb1PFm0Vg8KQqr7k%3D&reserved=0>)

  *   M content/en/blog/2022/metrics-announcement.md<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry.io%2Fpull%2F1361%2Ffiles%23diff-60973b730fa8378e821450ff22e0d3c270bbdabf5b90c60e1fcffab7135da782&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zioU8Z4iMmZzl4904ZylEFXhaVVJrjcVtXKT%2Bumndeo%3D&reserved=0> (1)

Patch Links:

  *   https://github.com/open-telemetry/opentelemetry.io/pull/1361.patch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry.io%2Fpull%2F1361.patch&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z3lXhTHWtVkyOfpV3FNBNzBVxAxhNYc1gmtnEx9smU0%3D&reserved=0>
  *   https://github.com/open-telemetry/opentelemetry.io/pull/1361.diff<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopen-telemetry%2Fopentelemetry.io%2Fpull%2F1361.diff&data=05%7C01%7C%7C717868321fb542730cb008da38d836e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637884798532764250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yyE6FGPM6pBAjZWmqXv%2FJKoZMK1%2FVJIKodQSWe7UGoU%3D&reserved=0>

**Comment by chalin** [comment]
The blog post is live: https://opentelemetry.io/blog/2022/metrics-announcement/

**Comment by alolita** [comment]
Thanks! @chalin @austinlparker

**Pull request merged**
