### PR TITLE
Add Chronosphere to vendors

### PR DESCRIPTION
**Pull request by paigerduty**
😄 💚

### CODE REVIEW

**Comment by cartermp** [comment]
@paigerduty Thanks for the contribution! Two things:

* Could you sign the CLA?
* Is there a link or place in the Chronosphere docs that mentions OTLP support specifically? We're likely to audit this page to make sure each entry links to a docs page demonstrating OTLP support + Distro support if they're listed in the table. The page you linked does include the OTel logo, but doesn't mention anything about sending OTel directly to Chronosphere's endpoint.

**Comment by paigerduty** [comment]
**Could you sign the CLA?**
- absolutely! working on finding the right signing manager for my organizatoin

**Is there a link or place in the Chronosphere docs that mentions OTLP support specifically?** 
- oh gosh yeah let me see how quickly I can get a website update noting that!

**Comment by cartermp** [comment]
@paigerduty any updates here w.r.t. docs page and signing the CLA?

**Comment by svrnm** [comment]
@paigerduty any updates? If you can not sign the CLA please close the PR, if you need any assistance with signing the CLA please let us know.

**Comment by cartermp** [comment]
Closin' out since it's been a while -- please ping if you'd like this re-opened.

**Pull request closed without merging**
