### PR TITLE
Adjust visualizations for dark/light mode compatibility

### PR DESCRIPTION
**Pull request by SusanGithaigaN**
This pr resolves issue #5361 and adjusts the background color of the visualizations, ensuring they adapt to both light and dark modes. The overall color scheme and theme remain unchanged.

## Demo:

[Review visualizations for dark_light mode compatibility #5361.webm](https://github.com/user-attachments/assets/bd8a6a49-0468-4621-883a-98de7cc4a708)

### CODE REVIEW

**Comment by SusanGithaigaN** [comment]
Hi @svrnm, could you please review my pr for this issue.
Thank you

**Review by chalin — CHANGES_REQUESTED** [review]
Very interesting work, thanks @SusanGithaigaN.

I've noted that the new SVG files actually contain many embedded PNG elements when there were none before. It is as if parts (probably the icons) were converted to PNGs. So now, it's like we have a collection of PNGs wrapped in an SVG.

I'd rather preserve the original SVG. Make minimal updates to the SVG text (if any is required at all), so that the new color dependent CSS classes can kick in. How does that sound @SusanGithaigaN?

**Comment by SusanGithaigaN** [comment]
> kick

Thanks for the feedback. Lemme take a look and make the necessary changes

**Comment by chalin** [comment]
@SusanGithaigaN @svrnm - Here's an example of the kind of minimal changes I had in mind. I've done the update for only one of the images, you can work on the other images if you'd like:

- #5436

**Pull request closed without merging**
