### PR TITLE
add last9 to otel vendors.yaml

### PR DESCRIPTION
**Pull request by sahilk**
- Adding Last9 Levitate to the list of Vendors
- https://last9.io
- https://docs.last9.io/docs/levitate-integrations-opentelemetry

### CODE REVIEW

**Review by chalin — COMMENTED** [review]
You'll need to sign the CLA @sahilk.

**Comment by sahilk** [comment]
@chalin Done.

**Comment by sahilk** [comment]
@chalin No sweat at all! 😅🙏

**Comment by sahilk** [comment]
@chalin Sorry, but could you check who can merge this? Don't see anyone tagged above so unsure about this. Thanks!

**Review by cartermp — APPROVED** [review]

**Pull request merged**
