### PR TITLE
Update instructions for modifying collector config when running with docker compose

### PR DESCRIPTION
**Pull request by djaglowski**
This corresponds to changes in https://github.com/open-telemetry/opentelemetry-demo/pull/1142

### CODE REVIEW

**Review by cartermp — APPROVED** [review]
LGTM, will defer to @open-telemetry/demo-approvers on when to merge

**Review by julianocosta89 — APPROVED** [review]
LGTM 🚀 

Lets just wait this one to get merged: https://github.com/open-telemetry/opentelemetry-demo/pull/1142

**Review by reyang — APPROVED** [review]

**Review by mviitane — APPROVED** [review]
As I commented [here](https://github.com/open-telemetry/opentelemetry-demo/pull/1142#issuecomment-1736769089), a picture would be nice to show the interaction with all config files. With 3 config files it gets complex anyway, whatever the setup will be.

**Comment by cartermp** [comment]
@djaglowski I fixed conflicts, but the upstream you're linking to is closed. Do you still want this in?

**Comment by djaglowski** [comment]
My recommendations were not accepted upstream so I'll close this as well.

**Pull request closed without merging**
