### PR TITLE
Update to spec 1.26.0 and semconv 1.22.0 at the SAME time

### PR DESCRIPTION
**Pull request by chalin**
- Closes #3387 by superseding it
- Closes #3386 by superseding it
- Updates both submodules at the same time since they are mutually dependent on each other. I suspect that this will probably always be the case but we should confirm with the spec and semconv folks.

**Preview**:

- https://deploy-preview-3388--opentelemetry.netlify.app/docs/specs/
- https://deploy-preview-3388--opentelemetry.netlify.app/schemas/1.22.0/

/cc @svrnm

### CODE REVIEW

**Comment by chalin** [comment]
An OpAMP semconv link is invalid, and is breaking the build (because we have build-time link checking for cross-spec links -- something to be revisited soon). So, atm, we're waiting on:

- https://github.com/open-telemetry/opamp-spec/pull/171

**Review by svrnm — APPROVED** [review]
lgtm, I'll approve this now so you can merge it when ever the dependencies are fixed

**Comment by tigrannajaryan** [comment]
> So, atm, we're waiting on:
> 
> * [[editorial] specification: fix semconv link opamp-spec#171](https://github.com/open-telemetry/opamp-spec/pull/171)

Merged.

**Review by reyang — APPROVED** [review]

**Comment by chalin** [comment]
So that we can get schema 1.22.0 out, I've disabled some link checks etc. I'll reenable them via:

- #3392

**Pull request merged**
