### PR TITLE
Add Apache SkyWalking to the ecosystem list.

### PR DESCRIPTION
**Pull request by wu-sheng**
SkyWalking has had native OpenTelemetry's OTLP support fo months.

### CODE REVIEW

**Comment by cartermp** [comment]
Is SkyWalking a vendor or an OSS project you can self host?

**Comment by wu-sheng** [comment]
OSS project.

**Comment by cartermp** [comment]
Hmm, in this case I think it makes more sense to list it under the [Ecosystem](https://opentelemetry.io/ecosystem/integrations/) page, since vendors are typically products that you pay to use.

**Comment by wu-sheng** [comment]
> Hmm, in this case I think it makes more sense to list it under the [Ecosystem](https://opentelemetry.io/ecosystem/integrations/) page, since vendors are typically products that you pay to use.

Got it. I have moved the project to ecosystem list. PTAL.

**Comment by wu-sheng** [comment]
I can see the preview build fails due to 

```
9:56:24 AM: [warn] content-modules/opentelemetry-go/website_docs/exporters.md
9:56:24 AM: [warn] content-modules/opentelemetry-go/website_docs/getting-started.md
9:56:24 AM: [warn] content-modules/opentelemetry-go/website_docs/libraries.md
9:56:24 AM: [warn] content-modules/opentelemetry-go/website_docs/manual.md
9:56:29 AM: [warn] Code style issues found in 4 files. Forgot to run Prettier?
```

But it seems not from my changes. Is something broken for main branch?

**Comment by cartermp** [comment]
Yeah, we added formatting to CI and it affects existing PRs. If you run `npm run prettier:write` and commit the changes it should go green.

**Comment by wu-sheng** [comment]
Those files belong to another repo(git submodule to opentelemetry-go). I bumped up the submodule(telemetry-go), it should be good now.

**Comment by wu-sheng** [comment]
I think this time is good.

**Comment by svrnm** [comment]
Please remove the changes to `content-modules/opentelemetry-go`, if files there are breaking the workflow we need to fix this on our end. cc @chalin

**Comment by wu-sheng** [comment]
So, you want me to revert sub module change and keep CI fails? Or I need to wait for another fix? @svrnm

**Comment by svrnm** [comment]
> So, you want me to revert sub module change and keep CI fails? Or I need to wait for another fix? @svrnm

Yes, individual PRs should not touch the content modules, if the CI still fails, we need to give this a separate look.

**Comment by chalin** [comment]
Hi. I believe that the source of the problem is that you merged from main earlier. What you need to is is **rebase** from main. Give that a try and let us know how it works out (it can be a bit trick to recover from a merge).

**Comment by wu-sheng** [comment]
I think I make the submodule back to the current main branch. Now it works. Thanks for your help.

**Comment by chalin** [comment]
Yes, good progress! But this PR still isn't a clean rebase because it contains changes to the community repo:

> image


Please fix that as well.

**Comment by wu-sheng** [comment]
> Yes, good progress! But this PR still isn't a clean rebase because it contains changes to the community repo:
> 
> > image
> 
> Please fix that as well.

Reverted.

**Review by chalin — APPROVED** [review]
LGTM (in terms of the PR being clean now), but I'll let @cartermp and @svrnm have the final word

**Comment by svrnm** [comment]
looks good to me 👍

**Comment by chalin** [comment]
@svrnm, FYI, it seems that you merged as means of updating the branch:

> image

Generally speaking, it's important to rebase, not merge:

> image

Why? Well, we've had a number of PRs get into muddled states because of merges.

I've enabled "Require linear history" for the main branch. Hopefully that'll cause the "merge" option to be excluded. We can discuss further during today's Comms meeting if you feel the need.

Thanks!

**Pull request merged**
