### PR TITLE
Update semantic-conventions version to v1.27.0

### PR DESCRIPTION
**Pull request by opentelemetrybot**
Update semantic-conventions version to `v1.27.0`.

See https://github.com/open-telemetry/semantic-conventions/releases/tag/v1.27.0.

### CODE REVIEW

**Review by chalin — CHANGES_REQUESTED** [review]
It seems like some links need to be manually fixed. I'm investigating.

**Comment by chalin** [comment]
There are invalid anchor ID in the semconv docs, for details, see:

- https://github.com/open-telemetry/semantic-conventions/issues/1313

I'll be fixing the other issues shortly.

**Review by chalin — APPROVED** [review]
All checks are passing now. Had to patch the `adjust-pages.pl` script.

@open-telemetry/docs-ja-approvers - can I get a second approval here, thx.

/cc @open-telemetry/specs-semconv-approvers

**Review by theletterf — APPROVED** [review]

**Review by lmolkova — APPROVED** [review]

**Comment by chalin** [comment]
All GH checks are passing. Netlify build seems to be stuck (since over an hour ago). I'm going to merge now, and will double check that the main build is ok.

Heads up that that I have some cleanup to do in the `adjust-pages.pl` script. I'll do that in a followup PR.

**Comment by chalin** [comment]
Hmm, the build is green https://app.netlify.com/teams/opentelemetry/builds/66ad423d73551f00087eb5d7:

> image

But there are a bunch of external links that don't show up in the refcache. I'll investigate that separately.

**Comment by chalin** [comment]
FYI, the followup issue (unrelated to this PR) is:

- #4942

**Pull request merged**
